### ISSUE TITLE
windows: .zip containing symlinks isn't extracted properly (F J O R D S)

### ISSUE THREAD

**Issue by davvves** [itchio/itch#1026]
<details>
<summary>
[2016-11-28 @ 22:54:32.278] [butler] butler error: *errors.errorString <nil>
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/zip.go:149 (0x597fe0)
</summary>
Caption                    OSArchitecture  Version     
Microsoft Windows 10 Home  64-bit          10.0.14393  

Caption                               MaxClockSpeed  Name                                       
Intel64 Family 6 Model 94 Stepping 3  2601           Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz  

Name                      
NVIDIA GeForce GTX 960M   
Intel(R) HD Graphics 530  

diego out

[2016-11-28 @ 22:54:11.426] [ibrew] isolate: upgrading '1.3.0' => '1.5.0'
[2016-11-28 @ 22:54:11.429] [ibrew] isolate: downloading '1.5.0' from https://dl.itch.ovh/isolate/windows-386/v1.5.0/isolate.7z
[2016-11-28 @ 22:54:11.430] [ibrew/net] downloading https://dl.itch.ovh/isolate/windows-386/v1.5.0/isolate.7z to C:\Users\David\AppData\Roaming\itch\bin\isolate.7z
[2016-11-28 @ 22:54:11.430] [ibrew] butler: upgrading '1.5.1' => '1.6.0'
[2016-11-28 @ 22:54:11.430] [ibrew] butler: downloading '1.6.0' from https://dl.itch.ovh/butler/windows-386/v1.6.0/butler.7z
[2016-11-28 @ 22:54:11.430] [ibrew/net] downloading https://dl.itch.ovh/butler/windows-386/v1.6.0/butler.7z to C:\Users\David\AppData\Roaming\itch\bin\butler.7z
[2016-11-28 @ 22:54:11.446] [ibrew] elevate: have latest (1.0.0)
[2016-11-28 @ 22:54:11.530] [locales] HTTP GET https://locales.itch.ovh/itch/en.json: 200
[2016-11-28 @ 22:54:11.530] [locales] Saving fresh en locale to C:\Users\David\AppData\Roaming\itch\locales\en.json
[2016-11-28 @ 22:54:11.546] [ibrew/net] downloaded 23 KB / 23 KB (23646 bytes)
[2016-11-28 @ 22:54:11.546] [locales] HTTP GET https://locales.itch.ovh/itch/en.json: 200
[2016-11-28 @ 22:54:11.546] [locales] Saving fresh en locale to C:\Users\David\AppData\Roaming\itch\locales\en.json
[2016-11-28 @ 22:54:11.608] [ibrew] isolate: extracting 7z archive
[2016-11-28 @ 22:54:12.016] [ibrew/net] downloaded 2.95 MB / 2.95 MB (3097931 bytes)
[2016-11-28 @ 22:54:12.093] [ibrew] butler: extracting 7z archive
[2016-11-28 @ 22:54:12.211] [ibrew] isolate: cleaning up 7z archive
[2016-11-28 @ 22:54:12.211] [ibrew] isolate: installed!
[2016-11-28 @ 22:54:12.451] [locales] Failed to load locale from C:\Users\David\AppData\Local\itch\app-20.0.2\resources\app.asar\app\static\locales\en-US.json: Error: ENOENT, app\static\locales\en-US.json not found in C:\Users\David\AppData\Local\itch\app-20.0.2\resources\app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.fs.readFile (ELECTRON_ASAR.js:468:16)
    at Promise (C:\Users\David\AppData\Local\itch\app-20.0.2\resources\app.asar\appsrc\localizer\ifs.ts:8:8)
    at Object.<anonymous> (C:\Users\David\AppData\Local\itch\app-20.0.2\resources\app.asar\appsrc\localizer\ifs.ts:7:16)
    at next (<anonymous>)
    at C:\Users\David\AppData\Local\itch\app-20.0.2\resources\app.asar\app\localizer\ifs.js:7:65
    at __awaiter (C:\Users\David\AppData\Local\itch\app-20.0.2\resources\app.asar\app\localizer\ifs.js:3:12)
    at Object.readFile (C:\Users\David\AppData\Local\itch\app-20.0.2\resources\app.asar\app\localizer\ifs.js:12:12)
    at C:\Users\David\AppData\Local\itch\app-20.0.2\resources\app.asar\appsrc\reactors\locales.ts:70:31
    at next (<anonymous>)
    at fulfilled (C:\Users\David\AppData\Local\itch\app-20.0.2\resources\app.asar\app\reactors\locales.js:4:58)
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[2016-11-28 @ 22:54:12.466] [locales] Waiting a bit before downloading en locale...
[2016-11-28 @ 22:54:12.714] [ibrew] butler: cleaning up 7z archive
[2016-11-28 @ 22:54:12.714] [ibrew] butler: running sanity check {"command":"butler","args":["-V"]}
[2016-11-28 @ 22:54:12.951] [ibrew] butler: installed!
[2016-11-28 @ 22:54:12.951] [reactors/setup] all deps done
[2016-11-28 @ 22:54:13.467] [locales] Downloading fresh locale file from https://locales.itch.ovh/itch/en.json
[2016-11-28 @ 22:54:13.607] [locales] HTTP GET https://locales.itch.ovh/itch/en.json: 200
[2016-11-28 @ 22:54:13.613] [locales] Saving fresh en locale to C:\Users\David\AppData\Roaming\itch\locales\en.json
[2016-11-28 @ 22:54:15.010] [reactors/main-window] Ready to show!
[2016-11-28 @ 22:54:15.011] [reactors/main-window] No devtools
[2016-11-28 @ 22:54:15.011] [reactors/main-window] Sending windowReady with id 1
[2016-11-28 @ 22:54:15.022] [reactors/self-update] Installed!
[2016-11-28 @ 22:54:15.034] [reactors/self-update] Update feed: https://nuts.itch.zone/update/win32_ia32/20.0.2
[2016-11-28 @ 22:54:15.038] [reactors/navigation] Not logged in, not saving tabs yet...
[2016-11-28 @ 22:54:15.043] [reactors/fetch] Not logged in, not fetching anything yet
[2016-11-28 @ 22:54:15.054] [reactors/navigation] Not logged in, not saving tabs yet...
[2016-11-28 @ 22:54:15.055] [reactors/navigation] Not logged in, not saving tabs yet...
[2016-11-28 @ 22:54:15.712] [reactors/fetch] Fetching the usuals
[2016-11-28 @ 22:54:15.872] [navigation] got user db ready
[2016-11-28 @ 22:54:15.880] [reactors/navigation] Session ready! looking for tabs to restore
[2016-11-28 @ 22:54:15.881] [reactors/navigation] Restoring 9 tabs
[2016-11-28 @ 22:54:16.410] [reactors/perf] preboot -> boot        = 331 ms
[2016-11-28 @ 22:54:16.410] [reactors/perf] boot    -> login       = 7212 ms
[2016-11-28 @ 22:54:16.410] [reactors/perf] login   -> first page  = 998 ms
[2016-11-28 @ 22:54:17.037] [reactors/self-update] Checking...
[2016-11-28 @ 22:54:17.305] [reactors/self-update] HTTP GET https://nuts.itch.zone/update/win32_ia32/20.0.2: 200
[2016-11-28 @ 22:54:29.904] [reactors/tasks] No cave for 397, attempting install
[2016-11-28 @ 22:54:29.907] [reactors/tasks] About to start find-upload (c07bfbb8-89b5-43e3-9cae-289ed9faae58)
[2016-11-28 @ 22:54:29.908] [reactors/tasks] Starting find-upload (c07bfbb8-89b5-43e3-9cae-289ed9faae58)...
[2016-11-28 @ 22:54:29.994] [tasks/find-upload] got a list of 2 uploads (with download key)
[2016-11-28 @ 22:54:29.994] [tasks/find-upload] final uploads: [
  {
    "filename": "SHARECART1000.zip",
    "updatedAt": "2015-12-19 13:59:54",
    "size": 18643080,
    "id": 918,
    "pOsx": true,
    "createdAt": "2013-11-16 05:03:27",
    "pWindows": true,
    "pAndroid": false,
    "position": 1,
    "pLinux": false,
    "type": "default",
    "gameId": 397,
    "preorder": false,
    "demo": false,
    "score": 600
  }
]
[2016-11-28 @ 22:54:29.994] [reactors/tasks] Checking results for find-upload (c07bfbb8-89b5-43e3-9cae-289ed9faae58)...
[2016-11-28 @ 22:54:29.994] [reactors/tasks] Task results: {
  "uploads": [
    {
      "filename": "SHARECART1000.zip",
      "updatedAt": "2015-12-19 13:59:54",
      "size": 18643080,
      "id": 918,
      "pOsx": true,
      "createdAt": "2013-11-16 05:03:27",
      "pWindows": true,
      "pAndroid": false,
      "position": 1,
      "pLinux": false,
      "type": "default",
      "gameId": 397,
      "preorder": false,
      "demo": false,
      "score": 600
    }
  ],
  "downloadKey": {
    "updatedAt": "2016-11-27 14:51:13",
    "downloads": 9,
    "id": 1727581,
    "purchaseId": 794825,
    "gameId": 397,
    "createdAt": "2016-11-27 14:51:13"
  }
}
[2016-11-28 @ 22:54:29.994] [reactors/tasks] Task ended, err: <none>
[2016-11-28 @ 22:54:29.999] [reactors/tasks] Should download 918, has dl key ? true
[2016-11-28 @ 22:54:30.197] [download-watcher] d4f545cc-5354-446f-a7fe-bdb4c09bfc7b is the new active download
[2016-11-28 @ 22:54:30.197] [download-watcher] Starting download...
[2016-11-28 @ 22:54:31.263] [butler] butler: All 18 MiB already there
[2016-11-28 @ 22:54:31.268] [download-watcher] Download ended, err: <none>
[2016-11-28 @ 22:54:31.270] [reactors/tasks] Download finished, installing..
[2016-11-28 @ 22:54:31.272] [reactors/tasks] About to start install (e3f086dd-48f1-45e2-b301-3c4c5df6e19e)
[2016-11-28 @ 22:54:31.313] [reactors/tasks] Starting install (e3f086dd-48f1-45e2-b301-3c4c5df6e19e)...
[2016-11-28 @ 22:54:31.317] [download-watcher] Download done!
[2016-11-28 @ 22:54:31.321] [tasks/install] upgrading from build id undefined => build id undefined
[2016-11-28 @ 22:54:31.322] [tasks/install] comparing mtimes, installed = NaN, archive = Sun Nov 27 2016 09:02:23 GMT-0600 (Central Standard Time)
[2016-11-28 @ 22:54:31.324] [install/core] retrieving installer type of C:\Users\David\AppData\Roaming\itch\downloads\918.zip from cache
[2016-11-28 @ 22:54:31.324] [install/core] invalid installer name stored: undefined - discarding
[2016-11-28 @ 22:54:31.365] [install/core] sniffed type {"ext":"zip","mime":"application/zip"} for C:\Users\David\AppData\Roaming\itch\downloads\918.zip
[2016-11-28 @ 22:54:31.457] [download-watcher] Cancelling/clearing out last download
[2016-11-28 @ 22:54:31.544] [installers/archive] extracting archive 'C:\Users\David\AppData\Roaming\itch\downloads\918.zip' to 'C:\Users\David\AppData\Roaming\itch\downloads\918.zip-stage'
[2016-11-28 @ 22:54:31.624] [util/extract] Using butler to extract zip
[2016-11-28 @ 22:54:31.700] [butler] butler: ∙ Extracting zip C:\Users\David\AppData\Roaming\itch\downloads\918.zip to C:\Users\David\AppData\Roaming\itch\downloads\918.zip-stage
[2016-11-28 @ 22:54:32.278] [butler] butler error: *errors.errorString <nil>
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/zip.go:149 (0x597fe0)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/archiver.go:72 (0x596947)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/archiver.go:63 (0x59682a)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/unzip.go:17 (0x419ab7)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:488 (0x41c18f)
C:/Go/src/runtime/proc.go:183 (0x45045e)
C:/Go/src/runtime/asm_386.s:1612 (0x47a281)

[2016-11-28 @ 22:54:32.282] [reactors/tasks] Task threw
[2016-11-28 @ 22:54:32.282] [reactors/tasks] Task ended, err: *errors.errorString <nil>
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/zip.go:149 (0x597fe0)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/archiver.go:72 (0x596947)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/archiver.go:63 (0x59682a)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/unzip.go:17 (0x419ab7)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:488 (0x41c18f)
C:/Go/src/runtime/proc.go:183 (0x45045e)
C:/Go/src/runtime/asm_386.s:1612 (0x47a281)

[2016-11-28 @ 22:54:32.282] [reactors/tasks] Error in task install: *errors.errorString <nil>
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/zip.go:149 (0x597fe0)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/archiver.go:72 (0x596947)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/archiver.go:63 (0x59682a)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/unzip.go:17 (0x419ab7)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:488 (0x41c18f)
C:/Go/src/runtime/proc.go:183 (0x45045e)
C:/Go/src/runtime/asm_386.s:1612 (0x47a281)

[2016-11-28 @ 22:54:32.282] [reactors/tasks] Install failed for fresh cave, destroying
[2016-11-28 @ 22:54:32.284] [reactors/tasks] Error in install: *errors.errorString <nil>
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/zip.go:149 (0x597fe0)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/archiver.go:72 (0x596947)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/archiver/archiver.go:63 (0x59682a)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/unzip.go:17 (0x419ab7)
C:/Multi-Runner/builds/58469115/0/itchio/butler/src/github.com/itchio/butler/main.go:488 (0x41c18f)
C:/Go/src/runtime/proc.go:183 (0x45045e)
C:/Go/src/runtime/asm_386.s:1612 (0x47a281)
</details>

**Comment by fasterthanlime** [comment]
I just released a new version of butler that solves this issue.

Quitting the itch app (Ctrl+Q, or right click tray icon -> Quit, *don't just close the window*) then starting it again will update butler. Can you confirm this is solved once you try it? Thanks!

**Comment by davvves** [comment]
Confirmed solved
