### ISSUE TITLE
spawn df ENFILE

### ISSUE THREAD

**Issue by siimorasmae** [itchio/itch#1078]
Event log:

```
Error: spawn df ENFILE
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by fasterthanlime** [comment]
Which exact version of macOS ?

Output of `which df` and `ls -lhA $(which df)` ?
