### ISSUE TITLE
🏁 Feedback v21.0.4

### ISSUE THREAD

**Issue by dmbsk** [itchio/itch#1079]
Event log:

```
Error: ENOSPC: no space left on device, write
    at Error (native)
From previous event:
    at Object.<anonymous> (C:\Users\towek\AppData\Local\itch\app-21.0.4\resources\app.asar\appsrc\util\sf.ts:144:21)
    at next (<anonymous>)
    at fulfilled (C:\Users\towek\AppData\Local\itch\app-21.0.4\resources\app.asar\app\util\sf.js:4:58)
```

**Comment by fasterthanlime** [comment]
Your disk is full :)

The app should handle it better - but that's the source of your problem.

**Comment by fasterthanlime** [comment]
Duplicate of #874 / #801
