### ISSUE TITLE
🏁 Feedback v23.1.0

### ISSUE THREAD

**Issue by deathishere420** [itchio/itch#1115]
Event log:

```
Error: EBUSY: resource busy or locked, unlink 'C:\Users\adew7\AppData\Roaming\itch\apps\HERO - A Game About Password Security\HERO_win\.itch\temp\NVIDIA Corporation\NV_Cache\fc477b767efc6bb3a77c27af289308_fce8395c8fd8a86e_d9e267694cee1255_0_0.bin'
    at Error (native)
From previous event:
    at Object.<anonymous> (C:\Users\adew7\AppData\Local\itch\app-23.1.0\resources\app.asar\appsrc\util\sf.ts:228:20)
    at next (<anonymous>)
    at C:\Users\adew7\AppData\Local\itch\app-23.1.0\resources\app.asar\app\util\sf.js:15:65
    at __awaiter (C:\Users\adew7\AppData\Local\itch\app-23.1.0\resources\app.asar\app\util\sf.js:11:12)
    at unlink (C:\Users\adew7\AppData\Local\itch\app-23.1.0\resources\app.asar\appsrc\util\sf.ts:226:41)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Object.<anonymous> (C:\Users\adew7\AppData\Local\itch\app-23.1.0\resources\app.asar\appsrc\util\sf.ts:230:37)
    at next (<anonymous>)
    at fulfilled (C:\Users\adew7\AppData\Local\itch\app-23.1.0\resources\app.asar\app\util\sf.js:12:58)
```

**Comment by fasterthanlime** [comment]
Interesting! A duplicate of #1109, but on another game. I'm closing this one in favor of the first one but I'll definitely take a look!
