### ISSUE TITLE
🏁 Feedback v23.4.0

### ISSUE THREAD

**Issue by maceman1984** [itchio/itch#1205]
Event log:

```
Error: ENOENT: no such file or directory, unlink 'C:\Users\Stephen\AppData\Roaming\itch\users\48120\marketdb\collections\165847'
    at Object.<anonymous> (C:\Users\Stephen\AppData\Local\itch\app-23.4.0\resources\app.asar\appsrc\util\sf.ts:237:18)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Stephen\AppData\Local\itch\app-23.4.0\resources\app.asar\app\util\sf.js:4:58)
```

**Comment by fasterthanlime** [comment]
itch v25 is out, it uses a proper database instead of writing files directly, so that error isn't possible anymore.

You can get it from https://itch.io/app
