### ISSUE TITLE
net::ERR_NETWORK_CHANGED when coming back from sleep

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1229]
Windows 10, sqlite-first branch @ 8752dae99c0f76872e2a67b71492af602677409b

```
$ WARNING: Promise with no error callback:6
{ exception: Error: net::ERR_NETWORK_CHANGED,
  error: null,
  promise:
   { _creator: null,
     _nextState: null,
     _state:
      { name: 'error',
        enter: [Function: enter],
        cancel: [Function: s],
        done: null,
        then: null,
        _completed: [Function: s],
        _error: [Function: s],
        _notify: [Function: m],
        _progress: [Function: s],
        _setCompleteValue: [Function: s],
        _setErrorValue: [Function: s] },
     _listeners: null,
     _value: Error: net::ERR_NETWORK_CHANGED,
     _isException: true,
     _errorId: 6,
     done: [Function: done],
     then: [Function: then] },
  handler: undefined,
  id: 6,
  parent: undefined }
Error: net::ERR_NETWORK_CHANGED
[uncaught exception in main]: Error: net::ERR_NETWORK_CHANGED

Error: net::ERR_NETWORK_CHANGED
Error: net::ERR_NETWORK_CHANGED

Error: net::ERR_NETWORK_CHANGED
    at Timeout._onTimeout (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:4
:29887)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by fasterthanlime** [comment]
An acute reader may observe that the crash is in fact in Visual Studio code, and not itch.

I'm not sure if it's reassuring or terrifying though.
