### ISSUE TITLE
localizer length undefined on `yarn start`

### ISSUE THREAD

**Issue by davej** [itchio/itch#1260]
Using Node 8 on MacOS 10.12.3 and following the [getting started guide](https://github.com/itchio/itch/blob/master/docs/hacking/getting-started.md). I get the following error on `yarn start`:

```
Uncaught exception: TypeError: Cannot read property 'length' of undefined
    at t (/Users/dave/code/itch/src/localizer/index.ts:11:16)
    at visitNode (/Users/dave/code/itch/src/reactors/menu.ts:60:22)
    at Function._.map._.collect (/Users/dave/code/itch/node_modules/underscore/underscore.js:172:24)
    at fleshOutTemplate (/Users/dave/code/itch/src/reactors/menu.ts:75:25)
    at Immediate.setImmediate (/Users/dave/code/itch/src/reactors/menu.ts:20:62)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

error Command failed with exit code 7.
```

**Comment by fasterthanlime** [comment]
That's on the master branch?

**Comment by davej** [comment]
Yes.

**Comment by davej** [comment]
Should I be using a release instead?

**Comment by fasterthanlime** [comment]
I guess that'd be best. 

I'm in the middle of big refactorings (the sqlite-first branch is 200+ commits ahead of master, but doesn't have feature parity). I can submit a patch to master if you really want to tho!

**Comment by davej** [comment]
No that's fine I can use a release. The Getting Started guide said to clone the repo so I assumed that master was supposed to be stable. Thanks for your help 👍
