### ISSUE TITLE
🏁 Feedback v23.4.1

### ISSUE THREAD

**Issue by freeone3000** [itchio/itch#1271]
Bad crash message for this.

Event log:

```
Error: ENOSPC: no space left on device, write
    at Object.<anonymous> (C:\Users\James\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\sf.ts:135:21)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\James\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\sf.js:4:58)
```

**Comment by fasterthanlime** [comment]
I agree it was a bad message.

In itch v25, the download would fail and show an error instead of crashing the whole app. Also, it shows you how much space you need to install a game and refuses to proceed if you don't have enough, so this shouldn't happen as much.
