### ISSUE TITLE
🏁 Feedback v23.1.0

### ISSUE THREAD

**Issue by hach-que** [itchio/itch#1275]
Event log:

```
Error: EBUSY: resource busy or locked, unlink 'C:\Users\June\AppData\Roaming\itch\apps\Protogame\.itch\temp\VSTelem\6498fd4c5c3c47e8a5981d2b8ff4429922704\tmp.edb'
    at Error (native)
From previous event:
    at Object.<anonymous> (C:\Users\June\AppData\Local\itch\app-23.1.0\resources\app.asar\appsrc\util\sf.ts:228:20)
    at next (<anonymous>)
    at C:\Users\June\AppData\Local\itch\app-23.1.0\resources\app.asar\app\util\sf.js:15:65
    at __awaiter (C:\Users\June\AppData\Local\itch\app-23.1.0\resources\app.asar\app\util\sf.js:11:12)
    at unlink (C:\Users\June\AppData\Local\itch\app-23.1.0\resources\app.asar\appsrc\util\sf.ts:226:41)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Object.<anonymous> (C:\Users\June\AppData\Local\itch\app-23.1.0\resources\app.asar\appsrc\util\sf.ts:230:37)
    at next (<anonymous>)
    at fulfilled (C:\Users\June\AppData\Local\itch\app-23.1.0\resources\app.asar\app\util\sf.js:12:58)
```

**Comment by fasterthanlime** [comment]
Oh look it's Visual Studio telemetry ruining everyone's day 😿 

(Did this happen after you just normally quit the game?)

**Comment by hach-que** [comment]
Yeah, I just quit the application normally.

**Comment by hach-que** [comment]
I don't have Visual Studio telemetry built into the application though, so I don't know why this would happen.

**Comment by fasterthanlime** [comment]
> I don't have Visual Studio telemetry built into the application though, so I don't know why this would happen.

Because it's on by default :'( https://www.infoq.com/news/2016/06/visual-cpp-telemetry

It's still an app bug though: it should be okay with the removal of the "temp" folder failing.

**Comment by fasterthanlime** [comment]
v25 makes the TEMP folder wipe a best-effort thing, it doesn't error out if it fails: https://github.com/itchio/butler/blob/ef2656c3bb774c6a61a7142f58280a13c062a846/endpoints/launch/launchers/native/native.go#L111
