### ISSUE TITLE
🏁 Uncaught Error: read ENOTCONN (v23.4.1)

### ISSUE THREAD

**Issue by FinalSparkGamestudios** [itchio/itch#1331]
Event log:

```
Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.<anonymous> (C:\Users\<user>\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:90:30)
    at Generator.next (<anonymous>)
    at C:\Users\<user>\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\<user>\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\<user>\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at Object.<anonymous> (C:\Users\<user>\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\os.ts:87:29)
```

**Comment by fasterthanlime** [comment]
Any antivirus software running?

What were you trying to do?

**Comment by FinalSparkGamestudios** [comment]
No antivirus running. Just ran the setup of the client. The client started and crashed on start. Running Win10 x64. Possible that something is conflicting with my nodejs installation?

**Comment by fasterthanlime** [comment]
So just on startup without doing anything?

Can you attach the `%APPDATA%/itch/logs/itch.txt` file ?

If you start it up again, does the same error happen every time ?

**Comment by FinalSparkGamestudios** [comment]
https://pastebin.com/78MbRehv

it happens every time I start up the program.

**Comment by fasterthanlime** [comment]
Interesting, the logs show that `wmic.exe` is not found in your $PATH

Did you edit your `PATH` at some point? Does it contain `C:\windows\system32\wbem` ? If not, can you edit it to contain that (Start menu -> Edit environment variables for your account, it's `;`-separated), quit the app completely (Ctrl+Q), start it up again and see if you still see the error?

**Comment by FinalSparkGamestudios** [comment]
ENV:
https://gyazo.com/c992ced3e932107b135e98c9149d41a3

Application:
https://gyazo.com/3b8d0c19be887d11ac70dc3b6e382783

**Comment by FinalSparkGamestudios** [comment]
Also, other socket applications work on my side with node js and stuff like that. Also found:

````If you are sure that nothing on your side of the TCP connection is closing the connection, then it sounds to me like the remote side is closing the connection.

ENOTCONN, as others have pointed out, simply means that the socket is not connected. This doesn't necessarily mean that connect failed. The socket may well have been connected previously, it just wasn't at the time of the call that resulted in ENOTCONN.

**Comment by fasterthanlime** [comment]
> Also, other socket applications work on my side with node js and stuff like that. Also found:

Thanks! That's not terribly useful here since we're not actually playing with sockets, it's just how nodejs does stdout/stderr redirection on Windows it seems.

> Application:
> https://gyazo.com/3b8d0c19be887d11ac70dc3b6e382783

Ah, so the problem is with unar.exe

Can you attach screenshots of the `%APPDATA%/itch/bin` and `%APPDATA%/itch/bin/unarchiver` folders?

Here are mine:

![bin](https://user-images.githubusercontent.com/7998310/28261743-bf4bf9e4-6ae0-11e7-9dce-d0ef80f8ca73.png)

![unarchiver](https://user-images.githubusercontent.com/7998310/28261751-c3347e1e-6ae0-11e7-8831-d1e28296052c.png)

**Comment by FinalSparkGamestudios** [comment]
![6ff7d4c563d81e483ddbb56fa03e6a8e](https://user-images.githubusercontent.com/7058926/28262100-20158578-6ae2-11e7-8654-94108a65a7de.png)
![missing2](https://user-images.githubusercontent.com/7058926/28262101-201d7710-6ae2-11e7-93af-94ccb2fb4f9c.PNG)

seems like a lot is missing there.

**Comment by FinalSparkGamestudios** [comment]
so it might be the setup failing?

**Comment by fasterthanlime** [comment]
Well, it downloads unarchiver properly, then extracts it properly, it properly adds `bin/unarchiver` to the $PATH, but now I'm starting to suspect that the $PATH ending with a semicolon initially is what could cause it to fail, let me try to reproduce.

**Comment by fasterthanlime** [comment]
I tried setting a PATH with a double semi-colon but it's not failing for me still:

![test-path](https://user-images.githubusercontent.com/7998310/28262460-537607a2-6ae3-11e7-9f7a-ef37bc6a5ea0.png)

Can you attach a screenshot of running the command `echo %PATH%` in a Command prompt (`cmd.exe` in Start menu)?

I'm finding it very strange that there's no `C:\Windows\System32` in yours for example.

My theory so far is that:

  * The PATH ends up being invalid somehow
  * Even though `unar.exe` is properly installed to the right directory, it can't be found in the PATH by Windows
  * Somehow that results in `ENOTCONN` ?

I'd also be interested in the output of `%APPDATA%\itch\bin\unarchiver\unar.exe --version` in a `cmd.exe` (as a screenshot)

**Comment by FinalSparkGamestudios** [comment]
![itchi2](https://user-images.githubusercontent.com/7058926/28262712-4e0428a2-6ae4-11e7-9db9-56683326be82.PNG)

**Comment by fasterthanlime** [comment]
When you start the app and it errs out - if you try to focus the app's main window and press Shift+F12, does a devtool window pop up?

If you can, navigate to the Console tool in there, type `process.env.PATH` then press Enter, and send a screenshot of the result

You can also try these:

![unar-commands](https://user-images.githubusercontent.com/7998310/28263014-8f27af24-6ae5-11e7-892e-0b99e0217cea.png)

**Comment by fasterthanlime** [comment]
For copy-paste purposes:

```
String(require("child_process").execSync(`${process.env.APPDATA}\\itch\\bin\\unarchiver\\unar.exe --version`))
"v1.10.1
"
String(require("child_process").execSync(`${process.env.APPDATA}\\itch\\bin\\unarchiver\\unar --version`))
"v1.10.1
"
String(require("child_process").execSync(`unar.exe --version`))
"v1.10.1
"
String(require("child_process").execSync(`unar --version`))
"v1.10.1
"
```

**Comment by FinalSparkGamestudios** [comment]
![dev toools](https://user-images.githubusercontent.com/7058926/28263234-4b5ed690-6ae6-11e7-915d-0e0648cd6ba0.PNG)

**Comment by fasterthanlime** [comment]
From cmd.exe, if you run `%LOCALAPPDATA%\itch\app-23.4.1\itch.exe`, does it behave any different?

**Comment by FinalSparkGamestudios** [comment]
<details>
<summary>
`C:\Users\marcf>%LOCALAPPDATA%\itch\app-23.4.1\itch.exe
</summary>

<pre>
C:\Users\marcf>
Mounting crash reporter
Fully mounted crash reporter
[2017-07-17 @ 12:11:01.686] [itch] itch 23.4.1 on electron 1.6.2
Processing 1 potential urls
Ignoring non-itchio url: C:\Users\marcf\AppData\Local\itch\app-23.4.1\itch.exe
[2017-07-17 @ 12:11:02.114] [xdg-mime] non-linux platform, skipping xdg-mime
[2017-07-17 @ 12:11:02.115] [preboot] Set up certificate error handler
[2017-07-17 @ 12:11:02.128] [locales] Waiting a bit before downloading en locale...
[2017-07-17 @ 12:11:03.118] [preboot] Could not detect proxy settings: proxy resolution timed out
[2017-07-17 @ 12:11:03.123] [reactors/setup] setup starting
[2017-07-17 @ 12:11:03.123] [ibrew] Augmenting $PATH: C:\Users\marcf\AppData\Roaming\itch\bin\unarchiver
Uncaught exception: Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:90:30)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\os.ts:87:29)
While catching: Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:90:30)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\os.ts:87:29)
While catching: Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:90:30)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\diego.ts:36:18
[ibrew] While checking version for unarchiver: spawn unar ENOENT
[2017-07-17 @ 12:11:03.193] [ibrew] unarchiver: missing, downloading latest
While catching: Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:90:30)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\diego.ts:36:18
[2017-07-17 @ 12:11:03.198] [locales] Downloading fresh locale file from https://locales.itch.ovh/itch/en.json
While catching: Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:90:30)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\diego.ts:36:18
[2017-07-17 @ 12:11:03.207] [preferences] imported preferences:
[2017-07-17 @ 12:11:03.208] [reactors/open-at-login] Updating login item settings, open: false, hidden: false
[2017-07-17 @ 12:11:03.210] [reactors/main-window] creating main window with icon: C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\static\images\window\itch\icon-32.png
[2017-07-17 @ 12:11:03.211] [reactors/main-window] cf. https://github.com/electron/electron/issues/6205
[2017-07-17 @ 12:11:03.227] [reactors/main-window] Ensuring {"x":-8,"y":-8,"width":1920,"height":1040} is inside a display
[2017-07-17 @ 12:11:03.228] [reactors/main-window] Display bounds: {"x":0,"y":0,"width":1920,"height":1080}
[2017-07-17 @ 12:11:03.228] [reactors/main-window] Nudging right
[2017-07-17 @ 12:11:03.228] [reactors/main-window] Nudging down
[2017-07-17 @ 12:11:03.229] [reactors/main-window] New bounds: {"x":0,"y":0,"width":1920,"height":1040}
[2017-07-17 @ 12:11:03.233] [reactors/main-window] Calling loadURL
[2017-07-17 @ 12:11:03.247] [locales] Waiting a bit before downloading en locale...
[2017-07-17 @ 12:11:04.248] [locales] Downloading fresh locale file from https://locales.itch.ovh/itch/en.json
[2017-07-17 @ 12:11:04.625] [ibrew] unarchiver: downloading '1.10.1' from https://dl.itch.ovh/unarchiver/windows-386/v1.10.1/unarchiver.tar.gz
[2017-07-17 @ 12:11:04.902] [locales] HTTP GET https://locales.itch.ovh/itch/en.json: 200
[2017-07-17 @ 12:11:04.903] [locales] Saving fresh en locale to C:\Users\marcf\AppData\Roaming\itch\locales\en.json
[2017-07-17 @ 12:11:04.906] [locales] HTTP GET https://locales.itch.ovh/itch/en.json: 200
[2017-07-17 @ 12:11:04.906] [locales] Saving fresh en locale to C:\Users\marcf\AppData\Roaming\itch\locales\en.json
[2017-07-17 @ 12:11:04.917] [net] downloaded 4.64 MB / 4.64 MB (4870053 bytes)
[2017-07-17 @ 12:11:05.062] [locales] Waiting a bit before downloading en locale...
[2017-07-17 @ 12:11:05.158] [net] unarchiver.tar.gz: expected SHA256: 47ed5bdd73b44d53b151b8f51ea7abc006e5bb59dd44eeba5cf608ac89217813
[2017-07-17 @ 12:11:05.239] [net] unarchiver.tar.gz:   actual SHA256: 47ed5bdd73b44d53b151b8f51ea7abc006e5bb59dd44eeba5cf608ac89217813
[2017-07-17 @ 12:11:05.239] [net] unarchiver.tar.gz: SHA256 checks out!
[2017-07-17 @ 12:11:05.240] [ibrew] unarchiver: extracting tar.gz archive
[2017-07-17 @ 12:11:05.516] [ibrew] unarchiver: cleaning up tar.gz arhcive
[2017-07-17 @ 12:11:05.518] [ibrew] unarchiver: running sanity check {"command":"unar","args":["--version"]}
While catching: Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:90:30
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at spawn (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at Function.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:189:22)
While catching: Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:90:30
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at spawn (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at Function.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:189:22)
[2017-07-17 @ 12:11:05.520] [reactors/setup] setup got error:
[2017-07-17 @ 12:11:05.669] [reactors/main-window] Ready to show!
[2017-07-17 @ 12:11:05.670] [reactors/main-window] No devtools
[2017-07-17 @ 12:11:05.670] [reactors/main-window] Sending windowReady with id 1
[2017-07-17 @ 12:11:05.672] [market] loading market db from C:\Users\marcf\AppData\Roaming\itch\marketdb
[2017-07-17 @ 12:11:05.672] [market] cleaning temporary files from C:\Users\marcf\AppData\Roaming\itch\marketdb
[2017-07-17 @ 12:11:05.683] [reactors/self-update] Installed!
[2017-07-17 @ 12:11:05.699] [reactors/self-update] Update feed: https://nuts.itch.zone/update/win32_ia32/23.4.1
[2017-07-17 @ 12:11:05.706] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-07-17 @ 12:11:05.710] [reactors/fetch] Not logged in, not fetching anything yet
While catching: Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:90:30)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\diskspace.ts:63:16)
[2017-07-17 @ 12:11:05.724] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-07-17 @ 12:11:05.725] [reactors] while reacting to QUERY_FREE_SPACE: Error: spawn wmic ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\spawn.ts:118:19)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\spawn.js:20:12)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\diskspace.ts:63:16)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\diskspace.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\diskspace.js:3:12)
    at Object.wmicRun (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\diskspace.ts:57:12)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\diskspace.ts:79:30)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\diskspace.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\diskspace.js:3:12)
    at Object.wmic (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\diskspace.ts:78:9)
    at Object.<anonymous> (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\appsrc\util\diskspace.ts:108:25)
    at Generator.next (<anonymous>)
    at C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\diskspace.js:7:71
    at __awaiter (C:\Users\marcf\AppData\Local\itch\app-23.4.1\resources\app.asar\app\util\diskspace.js:3:12)
[2017-07-17 @ 12:11:05.727] [reactors/navigation] Not logged in, not saving tabs yet...
[2017-07-17 @ 12:11:05.730] [market] loading records for C:\Users\marcf\AppData\Roaming\itch\marketdb
[2017-07-17 @ 12:11:05.746] [market] loaded 1 records in 16 ms
[2017-07-17 @ 12:11:05.746] [market] populating in-memory DB with disk records
[2017-07-17 @ 12:11:05.748] [market] done loading db from C:\Users\marcf\AppData\Roaming\itch\marketdb
[2017-07-17 @ 12:11:06.064] [locales] Downloading fresh locale file from https://locales.itch.ovh/itch/en.json
[2017-07-17 @ 12:11:06.065] [locales] HTTP GET https://locales.itch.ovh/itch/en.json: 200
[2017-07-17 @ 12:11:06.065] [locales] Saving fresh en locale to C:\Users\marcf\AppData\Roaming\itch\locales\en.json
[2017-07-17 @ 12:11:06.140] [diego] diego here, looking around
"wmic OS get Caption, Version, OSArchitecture" resisted us: spawn wmic ENOENT
"wmic cpu get Name, Caption, MaxClockSpeed" resisted us: spawn wmic ENOENT
"wmic path Win32_VideoController get Name" resisted us: spawn wmic ENOENT
diego out

[2017-07-17 @ 12:11:06.491] [market] loading market db from C:\Users\marcf\AppData\Roaming\itch\users\684785\marketdb
[2017-07-17 @ 12:11:06.491] [market] cleaning temporary files from C:\Users\marcf\AppData\Roaming\itch\users\684785\marketdb
[2017-07-17 @ 12:11:06.499] [market] loading records for C:\Users\marcf\AppData\Roaming\itch\users\684785\marketdb
[2017-07-17 @ 12:11:06.515] [market] loaded 7 records in 16 ms
[2017-07-17 @ 12:11:06.515] [market] populating in-memory DB with disk records
[2017-07-17 @ 12:11:06.516] [market] done loading db from C:\Users\marcf\AppData\Roaming\itch\users\684785\marketdb
[2017-07-17 @ 12:11:06.517] [navigation] got user db ready
[2017-07-17 @ 12:11:06.794] [reactors/fetch] Fetching the usuals
[2017-07-17 @ 12:11:07.699] [reactors/self-update] Checking...
[2017-07-17 @ 12:11:07.995] [reactors/self-update] HTTP GET https://nuts.itch.zone/update/win32_ia32/23.4.1: 200
[2017-07-17 @ 12:11:08.611] [reactors/main-window] Main window being closed
[2017-07-17 @ 12:11:08.612] [reactors/main-window] Close to tray enabled
[2017-07-17 @ 12:11:08.612] [reactors/main-window] Hiding main window`
</pre>
</details>

**Comment by fasterthanlime** [comment]
If you `set DIEGO_IS_ASLEEP=1` before running itch, does it start properly?

**Comment by fasterthanlime** [comment]
Oh my god I know what this issue is

**Comment by fasterthanlime** [comment]
@FinalSparkGamestudios Try this: https://itch.io/post/144319

**Comment by fasterthanlime** [comment]
See also https://github.com/atom/settings-view/issues/960

**Comment by FinalSparkGamestudios** [comment]
It seems that all the changes didn't fixed the issue with the startup.

**Comment by fasterthanlime** [comment]
> It seems that all the changes didn't fixed the issue with the startup.

If you open regedit.exe, navigate to `HKEY_LOCAL_MACHINE/SYSTEM/ControlSet001/Services/Null`, what's the value of `Start` ?

**Comment by fasterthanlime** [comment]
(Also, after fixing the registry, you might need to reboot)

**Comment by FinalSparkGamestudios** [comment]
I set it to start to 1. Yeah I should reboot. But can't atm due to work will try it later and reply if it worked.

**Comment by FinalSparkGamestudios** [comment]
Alright so after the registry change and restart everything seems to work now. Thank you very much for the help!

**Comment by fasterthanlime** [comment]
Phew, that's a relief! Thanks so much for the status update :star2:
