### ISSUE TITLE
HTML games do not run on linux

### ISSUE THREAD

**Issue by leafo** [itchio/itch#1350]
@fasterthanlime says it's because butler is out of date, we must verify html games work before launch

![](http://leafo.net/shotsnb/2017-07-19_11-13-11.png)

```
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968098,"msg":"itch 24.0.5 launching 'Beat 'em Up!' (#158791)","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968099,"msg":"No manifest at \"/home/leafo/.config/kitch/apps/Beat em Up/.itch.toml\"","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968099,"msg":"launching prepare for native","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968101,"msg":"not on windows, nothing to do","name":"prepare/native","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968113,"msg":"configuring /home/leafo/.config/kitch/apps/Beat em Up","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968113,"msg":"launching butler with args: [\"/home/leafo/.config/kitch/apps/Beat em Up\",\"--os-filter\",\"linux\",\"--arch-filter\",\"amd64\"]","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968125,"msg":"butler: > Collecting initial candidates","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968126,"msg":"butler: < Initial candidates are:\n{\n  \"basePath\": \"/home/leafo/.config/kitch/apps/Beat em Up\",\n  \"totalSize\": 1559397,\n  \"candidates\": [\n    {\n      \"path\": \"HTML/index.html\",\n      \"mode\": 438,\n      \"depth\": 2,\n      \"flavor\": \"html\",\n      \"size\": 2876\n    }\n  ]\n}","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968126,"msg":"butler: > Filtering for os linux, arch amd64","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968126,"msg":"butler: < After platform filter, candidates are:\n{\n  \"basePath\": \"/home/leafo/.config/kitch/apps/Beat em Up\",\n  \"totalSize\": 1559397,\n  \"candidates\": [\n    {\n      \"path\": \"HTML/index.html\",\n      \"depth\": 2,\n      \"flavor\": \"html\",\n      \"size\": 2876\n    }\n  ]\n}","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968126,"msg":"butler: < Configured in 783.949µs","v":1}
{"pid":24065,"hostname":"snotbox","level":30,"time":1500487968127,"msg":"verdict =\n{\n  \"basePath\": \"/home/leafo/.config/kitch/apps/Beat em Up\",\n  \"totalSize\": 1559397,\n  \"candidates\": [\n    {\n      \"path\": \"HTML/index.html\",\n      \"depth\": 2,\n      \"flavor\": \"html\",\n      \"size\": 2876\n    }\n  ]\n}","v":1}
{"pid":24065,"hostname":"snotbox","level":50,"time":1500487968145,"msg":"error while launching 4f85c88f-19a7-4e80-83a0-4b8f71807ccc: spawn EACCES","v":1}
{"pid":24065,"hostname":"snotbox","level":50,"time":1500487968147,"msg":"crashed with spawn EACCES","v":1}
{"pid":24065,"hostname":"snotbox","level":50,"time":1500487968147,"msg":"Error: spawn EACCES\n    at exports._errnoException (util.js:1050:11)\n    at ChildProcess.spawn (internal/child_process.js:319:11)\n    at Object.exports.spawn (child_process.js:390:9)\n    at Object.<anonymous> (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/src/os/spawn.ts:30:36)\n    at Generator.next (<anonymous>)\n    at Generator.tryCatcher (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)\n    at Object.<anonymous> (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/generators.js:201:15)\n    at Object.spawn [as default] (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/src/os/spawn.ts:88:21)\n    at /home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/src/reactors/launch/native.ts:68:43\n    at Generator.next (<anonymous>)\n    at Generator.tryCatcher (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)\n    at PromiseSpawn._promiseFulfilled (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/generators.js:97:49)\n    at Promise._settlePromise (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/leafo/Downloads/kitch-24.0.5-amd64/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)","v":1}
```

**Comment by fasterthanlime** [comment]
Was fixed by https://github.com/itchio/itch/commit/3251827a5de845016857f9c3826359bbe734ce71 closing
