### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by Ygdrad** [itchio/itch#1518]
Event log:

```
Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.<anonymous> (C:\Users\Ygdrad\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\spawn.ts:90:30)
    at Generator.next (<anonymous>)
    at C:\Users\Ygdrad\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\Ygdrad\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\Ygdrad\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\spawn.js:20:12)
    at Object.<anonymous> (C:\Users\Ygdrad\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\os.ts:87:29)
```

**Comment by Ygdrad** [comment]
Itch.io crashes when I try to launch it. same thing when I try installing it.

**Comment by fasterthanlime** [comment]
I think you may be having the problem described at https://itch.io/post/144319

---

If you open regedit.exe, navigate to `HKEY_LOCAL_MACHINE/SYSTEM/ControlSet001/Services/Null`, what's the value of `Start` ?

If it's 4, try setting it to 1 and rebooting.

**Comment by Ygdrad** [comment]
Yeah, it's the registry issue. Came back here to say it was solved.

**Comment by fasterthanlime** [comment]
Cool, thanks for reporting back!
