### ISSUE TITLE
[linux] Crash report for v0.9.4

### ISSUE THREAD

**Issue by trivoallan** [itchio/itch#152]
Crash log:

```
Pre-compiled, not using require hook.
in window-store done setting up action listeners
dom-ready o/
[Wed, 16 Dec 2015 14:29:09 GMT] [xdg-mime] registering self as default handler for itchio:// protocol
[Wed, 16 Dec 2015 14:29:09 GMT] [xdg-mime] querying default handler for itchio:// protocol
[Wed, 16 Dec 2015 14:29:09 GMT] [xdg-mime] query: itch.desktop
[Wed, 16 Dec 2015 14:29:09 GMT] [ibrew] 7za: have local version '9.20'
[Wed, 16 Dec 2015 14:29:09 GMT] [ibrew] 7za: cannot get latest version, skipping: status code: 404
[Wed, 16 Dec 2015 14:29:09 GMT] [ibrew] elevate: skipping, it's irrelevant on linux
[Wed, 16 Dec 2015 14:29:09 GMT] [ibrew] butler: missing, downloading latest
Nouvelle fenêtre ouverte dans la session du navigateur
[Wed, 16 Dec 2015 14:29:19 GMT] [setup-store] Setup failed: Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at TLSSocket.socketCloseListener (_http_client.js:235:23)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
From previous event:
    at self.normalize_version.version_equal.archive_name.download_to_file.get_latest_version.Promise (/opt/itch/resources/app.asar/app/util/ibrew.js:128:12)
    at executeBound (/opt/itch/resources/app.asar/node_modules/underscore/underscore.js:701:67)
    at bound (/opt/itch/resources/app.asar/node_modules/underscore/underscore.js:733:14)
    at Object.<anonymous> (/opt/itch/resources/app.asar/app/util/ibrew.js:145:16)
    at thenable (/opt/itch/resources/app.asar/app/ui/menu.js:7:142)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at Object.<anonymous> (/opt/itch/resources/app.asar/app/util/ibrew.js:238:66)
    at then (/opt/itch/resources/app.asar/app/ui/menu.js:14:23)
From previous event:
    at self.normalize_version.version_equal.archive_name.download_to_file.get_latest_version.Promise.fetch.Promise (/opt/itch/resources/app.asar/app/util/ibrew.js:141:12)
    at executeBound (/opt/itch/resources/app.asar/node_modules/underscore/underscore.js:701:67)
    at bound (/opt/itch/resources/app.asar/node_modules/underscore/underscore.js:733:14)
    at Array.map (native)
    at /opt/itch/resources/app.asar/app/stores/setup-store.js:49:42
    at thenable (/opt/itch/resources/app.asar/app/ui/menu.js:7:142)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at /opt/itch/resources/app.asar/app/stores/setup-store.js:48:25
    at then (/opt/itch/resources/app.asar/app/ui/menu.js:14:23)
From previous event:
    at install_deps (/opt/itch/resources/app.asar/app/stores/setup-store.js:45:10)
    at /opt/itch/resources/app.asar/app/stores/setup-store.js:82:16
    at thenable (/opt/itch/resources/app.asar/app/ui/menu.js:7:142)
Uncaught exception: TypeError: Cannot read property 'id' of null
    at cache_dashboard_games (/opt/itch/resources/app.asar/app/stores/game-store.js:51:41)
    at fetch_games (/opt/itch/resources/app.asar/app/stores/game-store.js:136:5)
    at /opt/itch/resources/app.asar/app/stores/store.js:87:12
    at /opt/itch/resources/app.asar/app/dispatcher/app-dispatcher.js:98:11
    at Array.forEach (native)
    at Dispatcher.dispatch (/opt/itch/resources/app.asar/app/dispatcher/app-dispatcher.js:95:36)
    at EventEmitter.<anonymous> (/opt/itch/resources/app.asar/app/dispatcher/app-dispatcher.js:109:10)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/opt/itch/resources/atom.asar/browser/api/lib/web-contents.js:85:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
app event: will-quit
app event: quit

```

**Comment by fasterthanlime** [comment]
@trivoallan c'est un mix de #120 (j'ai une idée) et de #137 :(

En attendant un vrai fix, tu peux essayer de simplement redémarrer l'appli une fois pour voir si ça marche? C'est un problème intermittent.

**Comment by trivoallan** [comment]
Le problème se pose toujours.

Précision : j'essaye de le lancer depuis un réseau d'entreprise. Tous les ports ne sont pas ouverts, je ne sais pas si ça joue.

**Comment by fasterthanlime** [comment]
@trivoallan toutes les connections se font sur les ports 443 (https pour l'API + le téléchargement des dépendances et des jeux eux-même) et possiblement 80 (pour certaines images).

J'ai changé la manière dont les requêtes asynchrones se déroulent à partir de 0.10.x, j'espère que la nouvelle version marchera mieux.

**Comment by trivoallan** [comment]
Ça fonctionne bien avec le version 0.10.2, merci :)

**Comment by fasterthanlime** [comment]
@trivoallan merci beaucoup pour le retour!
