### ISSUE TITLE
🐧 Kitch v24.6.0 hangs at launch at the Itch logo, but older versions work fine.

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch#1542]
These versions work:
- [Kitch v24.1.7](https://github.com/itchio/itch/issues/1446)
- Itch v23.4.2

When I upgraded to Kitch v24.6.0, it just hangs at the itch logo: ![vxc](https://user-images.githubusercontent.com/1646875/31208887-596a45a8-a94d-11e7-8156-b9b51132409a.png)

I have tried `rm -R ~/.config/kitch` and it did not change anything except for the default window location and size.

Log when launched from Terminal after removing `~/.config/kitch`: https://pastebin.com/FWsQHfbP

My OS is Linux, Xubuntu 16.04 64-bit.

**Comment by aaronfranke** [comment]
This error persists every time Kitch v24.6.0 is launched:
```
02:51:13.378 INFO (db) connecting to db /home/aaronfranke/.config/kitch/marketdb/local.db
02:51:13.420 ERROR (db) migration 1506341540 failed: SqliteError: no such column: buildId
    at DB.prepare (/usr/lib/kitch/resources/app.asar/src/db/db.ts:199:26)
    at Querier.all (/usr/lib/kitch/resources/app.asar/src/db/querier.ts:39:24)
    at Repository.all (/usr/lib/kitch/resources/app.asar/src/db/repository.ts:69:23)
    at 1506341540 (/usr/lib/kitch/resources/app.asar/src/db/migrations.ts:38:37)
    at Object.runMigrations (/usr/lib/kitch/resources/app.asar/src/db/migrator.ts:35:19)
    at migrateDatabase (/usr/lib/kitch/resources/app.asar/src/db/index.ts:57:28)
    at Object.connectDatabase (/usr/lib/kitch/resources/app.asar/src/db/index.ts:39:11)
    at App.<anonymous> (/usr/lib/kitch/resources/app.asar/src/metal.ts:95:22)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

**Comment by fasterthanlime** [comment]
Found the bug, it's unrelated to the failing migration (although that's good to know too!)

![image](https://user-images.githubusercontent.com/7998310/31216049-68d5ee88-a9b2-11e7-9ace-57ded510c25a.png)

This is due to incorrect [modclean patterns](https://github.com/itchio/itch/blob/master/release/modclean-patterns.js) but the strange part is: I'm pretty sure I fixed that in the past already :)

**Comment by fasterthanlime** [comment]
v24.8.0 is out, should fix that issue - please open a new one if you're still having trouble running it!

**Comment by aaronfranke** [comment]
Confirmed fixed.
