### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by joonjoonjoon** [itchio/itch#1544]
keep getting this error when trying to access this page
https://txt92.itch.io/planetardefensecommand

Event log:

```
Error: HTTP 404 /s8iRs3MSz5372NAPr46SjTI5X2uA89Vew3JdODWp/game/182050

stack:
Error: HTTP 404 /s8iRs3MSz5372NAPr46SjTI5X2uA89Vew3JdODWp/game/182050
    at Client.<anonymous> (C:\Users\joon\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\api.ts:87:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\joon\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\api.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by fasterthanlime** [comment]
We were having server issues earlier today, they've been resolved since!
