### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by ktyldev** [itchio/itch#1545]
Tried to access [https://eclipse-inc.itch.io/defend-the-kingdom](https://eclipse-inc.itch.io/defend-the-kingdom) through the app, got the `Aw, Snap!` page.

Event log:

```
Error: HTTP 404 /wJ7kF2bT2c8dhJY690b27ZEOvohkbvWT5Rgm9q34/game/182113

stack:
Error: HTTP 404 /wJ7kF2bT2c8dhJY690b27ZEOvohkbvWT5Rgm9q34/game/182113
    at Client.<anonymous> (C:\Users\Cat\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\api.ts:87:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Cat\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\api.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by fasterthanlime** [comment]
We were having server issues earlier today, they've been resolved since!
