### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by CSD39** [itchio/itch#1546]
Event log:

```
Error: HTTP 404 /63Yb41Xqi74O75Ln9VW1xc2e2osKO7kx8i7UQw2V/game/95965

stack:
Error: HTTP 404 /63Yb41Xqi74O75Ln9VW1xc2e2osKO7kx8i7UQw2V/game/95965
    at Client.<anonymous> (C:\Users\conne\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\api.ts:87:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\conne\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\api.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by fasterthanlime** [comment]
We were having server issues earlier today, they've been resolved since!
