### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by Kevinsillo** [itchio/itch#1547]
Event log:

```
Error: HTTP 404 /t673BwJs6CTuJ2T91uSk09ZaXEe0678r13rfOYwF/game/76077

stack:
Error: HTTP 404 /t673BwJs6CTuJ2T91uSk09ZaXEe0678r13rfOYwF/game/76077
    at Client.<anonymous> (C:\Users\Kevin\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\api.ts:87:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Kevin\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\api.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by fasterthanlime** [comment]
We were having server issues earlier today, they've been resolved since!
