### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by RaDiKalDev** [itchio/itch#1548]
Selecting Collections and then Autonauts:
(first time itch install and new itch account; added profile pic and then sought to install Autonauts via itch)
Event log:

```
Error: HTTP 404 /647ki3mVa17r9212S5g1FN0wJwT6ZiUV1VlzF6v5/collection/231393/games

stack:
Error: HTTP 404 /647ki3mVa17r9212S5g1FN0wJwT6ZiUV1VlzF6v5/collection/231393/games
    at Client.<anonymous> (C:\Users\Ron\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\api.ts:87:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Ron\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\api.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by fasterthanlime** [comment]
We were having server issues earlier today, they've been resolved since!
