### ISSUE TITLE
🏁 Feedback v23.4.2

### ISSUE THREAD

**Issue by KieranPont** [itchio/itch#1556]
Event log:

```
Error: read ENOTCONN
    at exports._errnoException (util.js:1022:11)
    at Socket._read (net.js:425:21)
    at Socket.Readable.read (_stream_readable.js:348:10)
    at Socket.read (net.js:308:43)
    at new Socket (net.js:188:12)
    at createSocket (internal/child_process.js:243:11)
    at internal/child_process.js:329:22
    at Array.forEach (native)
    at ChildProcess.spawn (internal/child_process.js:318:9)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.<anonymous> (C:\Users\kieranpont\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\spawn.ts:90:30)
    at Generator.next (<anonymous>)
    at C:\Users\kieranpont\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\spawn.js:7:71
    at __awaiter (C:\Users\kieranpont\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\spawn.js:3:12)
    at Object.spawn [as default] (C:\Users\kieranpont\AppData\Local\itch\app-23.4.2\resources\app.asar\app\util\spawn.js:20:12)
    at Object.<anonymous> (C:\Users\kieranpont\AppData\Local\itch\app-23.4.2\resources\app.asar\appsrc\util\os.ts:87:29)
```

**Comment by fasterthanlime** [comment]
This sounds like the same issue as this: https://github.com/itchio/itch/issues/1518

Can you try the instructions there, reboot, and report back if it's fixed?

**Comment by KieranPont** [comment]
Yes that worked thanks
