### ISSUE TITLE
[linux] Crash report for v0.9.4

### ISSUE THREAD

**Issue by gildo** [itchio/itch#159]
Crash log:

```
TypeError: db.find is not a function
    at cache_owned_games (/opt/itch/resources/app.asar/app/stores/game-store.js:41:13)
    at fetch_games (/opt/itch/resources/app.asar/app/stores/game-store.js:129:5)
    at /opt/itch/resources/app.asar/app/stores/store.js:87:12
    at /opt/itch/resources/app.asar/app/dispatcher/app-dispatcher.js:98:11
    at Array.forEach (native)
    at Dispatcher.dispatch (/opt/itch/resources/app.asar/app/dispatcher/app-dispatcher.js:95:36)
    at EventEmitter.<anonymous> (/opt/itch/resources/app.asar/app/dispatcher/app-dispatcher.js:109:10)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/opt/itch/resources/atom.asar/browser/api/lib/web-contents.js:85:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by fasterthanlime** [comment]
@gildo Can you remember what you were doing when it happened?

Does it happen on every start, or was it a one-time thing?

**Comment by gildo** [comment]
@fasterthanlime only at the first login

**Comment by fasterthanlime** [comment]
@gildo alright, I'll try & add a workaround. Thanks for the report

**Comment by gildo** [comment]
@fasterthanlime thank you :D
