### ISSUE TITLE
Compiling on Gentoo fails

### ISSUE THREAD

**Issue by noobpurple** [itchio/itch#1697]
I found an ebuild for Itch that pretty much follows exactly what the AUR PKGBUILD is doing for Arch, which I planned to do anyway if I couldn't find an existing ebuild. The ebuild [here](https://data.gpo.zugaina.org/hossie/games-util/itch/itch-23.4.0.ebuild) works, but it's outdated (v23.4.0). I put it in my local overlay, bumped the version number, and tried to build it, but it fails aftery trying to run "ts:default". 

```
Running "ts:default" (ts) task
Compiling...
Using tsc v2.7.1
/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:59841
                throw e;
                ^

Error: Debug Failure.
    at checkUnusedClassMembers (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:35757:38)
    at checkUnusedIdentifiers (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:35643:29)
    at checkSourceFileWorker (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:37913:21)
    at checkSourceFile (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:37891:13)
    at Object.forEach (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:260:30)
    at getDiagnosticsWorker (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:37957:16)
    at getDiagnostics (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:37934:24)
    at Object.getEmitResolver (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:20122:17)
    at emitWorker (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:59783:69)
    at /var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/node_modules/typescript/lib/tsc.js:59757:66

>> Error: tsc return code: 1
Warning: Task "ts:default" failed. Use --force to continue.

Aborted due to warnings.
☃ non-zero exit code: 3
/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/release/node_modules/munyx/index.js:19
    throw new Error('Exit code assertion failed, bailing out')
    ^

Error: Exit code assertion failed, bailing out
    at $ (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/release/node_modules/munyx/index.js:19:11)
    at Object.<anonymous> (/var/tmp/portage/games-util/itch-23.6.1/work/itch-23.6.1/release/ci-compile.js:16:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)


```

Portage reports that this was thrown while running `release/ci-compile.js`. I'd appreciate the help in figuring out what's going wrong here. Let me know if you need more info.

**Comment by fasterthanlime** [comment]
It looks like a crash in the typescript compiler itself, but 2.7.1 is more recent than anything I've seen (it's more recent that what master uses!)

v23 has typescript pinned to [a much older version](https://github.com/itchio/itch/blob/v23/package-lock.json#L5505-L5510), which probably compiles its sources fine.

However, `package-lock.json` wasn't supported in npm until v5, so maybe you have npm v4 on your system?

**Comment by noobpurple** [comment]
Oh man, thanks for that! I didn't think to check the npm version. Gentoo compiles nodejs-6.11.5 which came packaged with npm version 3.10.10. The next highest supported nodejs is 9.5.0, and unmasking that one to get an up-to-date npm fixed the problem. I'll update the ebuild to require a higher nodejs version. Thanks again!

If the ebuild breaks again in the future, do you want me to open another issue here or should that discussion be somewhere else?

**Comment by fasterthanlime** [comment]
> Oh man, thanks for that! I didn't think to check the npm version. Gentoo compiles nodejs-6.11.5 which came packaged with npm version 3.10.10. The next highest supported nodejs is 9.5.0, and unmasking that one to get an up-to-date npm fixed the problem. I'll update the ebuild to require a higher nodejs version. Thanks again!

Awesome, that's so good to hear!

> If the ebuild breaks again in the future, do you want me to open another issue here or should that discussion be somewhere else?

That is exactly the right place for these discussions, please do! 🌟
