### ISSUE TITLE
Never send on disconnected client

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1699]
```
unhandled rejection: Error: trying to send on disconnected client
    at Client.sendRaw (C:\msys64\home\amos\Dev\itch\node_modules\node-buse\lib\client.js:171:19)
    at Client.sendResult (C:\msys64\home\amos\Dev\itch\node_modules\node-buse\lib\client.js:167:14)
    at Promise.resolve.then.catch.e (C:\msys64\home\amos\Dev\itch\node_modules\node-buse\lib\client.js:262:22)
    at <anonymous>
```

Happened after force-closing an HTML game.

(Or if we do send on disconnect client, catch the exception somewhere and just log it, instead of crashing).

**Comment by fasterthanlime** [comment]
That hasn't been an issue in a long while.
