### ISSUE TITLE
🏁 Feedback v23.6.1

### ISSUE THREAD

**Issue by Fennecai** [itchio/itch#1703]
Event log:

```
Error: ENOSPC: no space left on device, write
    at Object.<anonymous> (C:\Users\aekna\AppData\Local\itch\app-23.6.1\resources\app.asar\appsrc\util\sf.ts:135:21)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\aekna\AppData\Local\itch\app-23.6.1\resources\app.asar\app\util\sf.js:4:58)
    at <anonymous>
```

**Comment by fasterthanlime** [comment]
You ran out of disk space!

Check out the `%APPDATA%/itch/apps/downloads` folder, itch v23.x doesn't clean it up properly so you might have quite a few files you're able to delete.

If you've just recently installed the app and haven't used it much then you probably need to make space elsewhere. If you have another disk you can add and set as default another install location in Preferences => Install locations.
