### ISSUE TITLE
🏁 Feedback v23.6.1

### ISSUE THREAD

**Issue by areinot** [itchio/itch#1771]
What is an "Invalid game" error?

Event log:
```
API Error: invalid game

stack:
API Error: invalid game
    at Client.<anonymous> (C:\Users\andre\AppData\Local\itch\app-23.6.1\resources\app.asar\appsrc\util\api.ts:93:13)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\andre\AppData\Local\itch\app-23.6.1\resources\app.asar\app\util\api.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by fasterthanlime** [comment]
Did this crash the app?

(The API returns "invalid game" whenever you're trying to access a game that you don't have access to or that just plain doesn't exist. It should never crash the app though)

**Comment by areinot** [comment]
I believe this was an itch app crash when I tried launching my game. Could be I was logged into the wrong account but the itch apps directory is shared? I'll close it until I can get you repro steps.
