### ISSUE TITLE
🏁 Feedback v23.6.3

### ISSUE THREAD

**Issue by AlphaRovic** [itchio/itch#1859]
Event log:

```
Error: EBUSY: resource busy or locked, unlink 'C:\Users\Lenovo\AppData\Roaming\itch\marketdb\caves\1a0b231a-0bb0-4f27-a4a4-ebf6740a9704.tmp0'
    at Object.<anonymous> (C:\Users\Lenovo\AppData\Local\itch\app-23.6.3\resources\app.asar\appsrc\util\sf.ts:237:18)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Lenovo\AppData\Local\itch\app-23.6.3\resources\app.asar\app\util\sf.js:4:58)
    at <anonymous>
```

**Comment by fasterthanlime** [comment]
v25 is out, it uses a proper database (sqlite), so this class of problems should no longer exist.
