### ISSUE TITLE
Figure out assignment to constant variable

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#1884]
```
17:41:33.334 ERROR (route) while reacting to openGameContextMenu: TypeError: Assignment to constant variable.
    at e.on (C:\msys64\home\amos\Dev\itch\dist\main\webpack:\src\main\reactors\context-menu.ts:11:3)
    at C:\msys64\home\amos\Dev\itch\dist\main\webpack:\src\common\util\route.ts:32:23
    at Timeout.setTimeout (C:\msys64\home\amos\Dev\itch\dist\main\webpack:\src\common\util\route.ts:28:5)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
Full error:  {}
17:42:33.257 ERROR (route) while reacting to analyzePage: TypeError: Assignment to constant variable.
    at m (C:\msys64\home\amos\Dev\itch\dist\main\webpack:\src\main\reactors\web-contents.ts:173:26)
    at <anonymous>
Full error:  {}
17:42:52.664 ERROR (route) while reacting to analyzePage: TypeError: Assignment to constant variable.
    at m (C:\msys64\home\amos\Dev\itch\dist\main\webpack:\src\main\reactors\web-contents.ts:173:26)
    at <anonymous>
Full error:  {}
17:42:53.613 INFO (download-dr
```

I suspect babel/uglify etc. are transpiling

```typescript
const {window} = blah;
```

...to something funky. Bad transpilers, don't do that.

**Comment by fasterthanlime** [comment]
nevermind, the problem is much more annoying
