### ISSUE TITLE
butlerd lifecycle improvements

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#2032]
When a computer goes to sleep, butlerd may close normally?

```
20:15:47.323 INFO (m/reac/updater) Scheduling next game update check for Fri Aug 03 2018 22:45:18 GMT+0200 (Romance Daylight Time)
(butlerd) no handler for notification Log
(butlerd) no handler for notification Log
(butlerd) no handler for notification Log
Uncaught network error: Error: net::ERR_ABORTED
Uncaught network error: Error: net::ERR_ABORTED

VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV

20:22:29.366 INFO (m/reac/setup) butlerd instance 1 has closed.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

07:27:41.583 INFO (m/reac/updater) Regularly scheduled check for game updates...
07:27:41.598 INFO (m/reac/updater) Scheduling next game update check for Sat Aug 04 2018 09:53:34 GMT+0200 (Romance Daylight Time)
[7008:0804/092742.268:WARNING:dns_config_service_win.cc(669)] Failed to read DnsConfig.
07:27:42.749 INFO (broth :: butler:windows-amd64-head) Using local, so, not upgrading.
07:27:44.762 WARN (broth :: itch-setup:windows-amd64-head) While checking for latest version: Error: net::ERR_INTERNET_DISCONNECTED
    at ClientRequest.req.on.error (C:\msys64\home\amos\Dev\itch\dist\main\main.bundle.js:12765:20)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at URLRequest._emitRequestEvent (C:\msys64\home\amos\Dev\itch\node_modules\electron\dist\resources\electron.asar\browser\api\net.js:90:24)
07:27:44.820 ERROR while reacting to checkForComponentUpdates: Error: Could not retrieve latest version of (itch-setup): net::ERR_INTERNET_DISCONNECTED
    at package_Package.doUpgrade (C:\msys64\home\amos\Dev\itch\dist\main\main.bundle.js:22053:19)
    at <anonymous>
EventSource error: Error: net::ERR_NETWORK_CHANGED
Caught butler error:
JavaScript stack: Error: net::ERR_NETWORK_CHANGED
07:27:50.682 ERROR while reacting to checkForGameUpdates: Error: net::ERR_NETWORK_CHANGED
Caught butler error:
JavaScript stack: Error: net::ERR_CONNECTION_REFUSED
07:35:17.087 WARN (m/reac/commons) While fetching commons: Error: net::ERR_CONNECTION_REFUSED
07:53:35.383 INFO (m/reac/updater) Regularly scheduled check for game updates...
07:53:35.398 INFO (m/reac/updater) Scheduling next game update check for Sat Aug 04 2018 10:19:13 GMT+0200 (Romance Daylight Time)
EventSource error: Error: net::ERR_CONNECTION_REFUSED
Caught butler error:
JavaScript stack: Error: net::ERR_CONNECTION_REFUSED
```

**Comment by fasterthanlime** [comment]
The idea is:

  * To check, at an interval, that we still have a butlerd instance (or that we're trying to start one)
  * If we don't have one and we're not trying to start one (and setup is done), start a new one
  * When logging `uncaught network errors` or `butler errors`, include timestamps
  * Write butler logs to a file somewhere, so we get messages about graceful shutdown, etc.
