### ISSUE TITLE
Console game doesn't open console

### ISSUE THREAD

**Issue by python-b5** [itchio/itch#2122]
My game "Restaurant Simulator (Sunset Diner)" ( https://python-b5.itch.io/restaurant ) works fine when I run the .exe normally, but inside the itch app no console window opens up. I don't really see the purpose of hiding the console window like this, as most game executables do it anyways. Maybe there could be an option for a console game?

**Comment by fasterthanlime** [comment]
~This is related to #2111~

**Comment by fasterthanlime** [comment]
Nevermind - for me the game doesn't launch, it crashes with:

```
$ ./restaurant.exe

[2360] Failed to execute script restaurant
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 149, in __init__
  File "ctypes\__init__.py", line 348, in __init__
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "restaurant.py", line 625, in <module>
  File "restaurant.py", line 260, in main
  File "site-packages\pyglet\media\sources\loader.py", line 63, in load
  File "site-packages\pyglet\media\sources\loader.py", line 93, in get_source_loader
  File "site-packages\pyglet\media\sources\loader.py", line 114, in have_avbin
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\python-b5\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\pyglet\media\sources\avbin.py", line 64, in <module>
  File "site-packages\pyglet\lib.py", line 137, in load_library
  File "ctypes\__init__.py", line 426, in LoadLibrary
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'avbin64'. Most probably this dynlib/dll was not found when the application was frozen.
Unexpected error loading library avbin64: Failed to load dynlib/dll 'avbin64'. Most probably this dynlib/dll was not found when the application was frozen.
```

Which leads me to think there's something wrong with how the game is distributed :) I do see a console window open and immediately close, when it's run via the itch app.

**Comment by python-b5** [comment]
Oh - I see the problem, AVBin is required for audio
