### ISSUE TITLE
🏁 RangeError: Invalid string length (v25.3.0)

### ISSUE THREAD

**Issue by skellitor301** [itchio/itch#2184]
Event log:

```
RangeError: Invalid string length
    at DestroyableTransform.transform [as _transform] (f:\Users\skellitor301pc\AppData\Local\itch\app-25.3.0\resources\app.asar\dist\main\main.bundle.js:13789:31)
    at DestroyableTransform.module.exports.Transform._read (f:\Users\skellitor301pc\AppData\Local\itch\app-25.3.0\resources\app.asar\dist\main\main.bundle.js:19766:10)
    at DestroyableTransform.module.exports.Transform._write (f:\Users\skellitor301pc\AppData\Local\itch\app-25.3.0\resources\app.asar\dist\main\main.bundle.js:19754:83)
    at doWrite (f:\Users\skellitor301pc\AppData\Local\itch\app-25.3.0\resources\app.asar\dist\main\main.bundle.js:19015:64)
    at writeOrBuffer (f:\Users\skellitor301pc\AppData\Local\itch\app-25.3.0\resources\app.asar\dist\main\main.bundle.js:19004:5)
    at DestroyableTransform.module.exports.Writable.write (f:\Users\skellitor301pc\AppData\Local\itch\app-25.3.0\resources\app.asar\dist\main\main.bundle.js:18921:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

**Comment by fasterthanlime** [comment]
Hey, thanks for the report!

Can you describe what were you doing when this happened?

**Comment by skellitor301** [comment]
I dont exactly recall to be honest, I think my computer was running slow

**Comment by fasterthanlime** [comment]
> I think my computer was running slow

Mhh that checks out - it seems like that error can happen when you're running dangerously low on RAM:

  * https://github.com/nodejs/help/issues/1061

...or when something larger than the max string limit is being processed, but I'm really curious how that could happen.

It doesn't look like there's an easy way to reproduce this, so I'll edit the title and close it for now. If it happens again for someone else, we'll have this as a reference point! 🌟
