### ISSUE TITLE
🍎 Feedback v37.0.1

### ISSUE THREAD

**Issue by mhealysmith** [itchio/itch#2317]
Event log:

```
Error: Uncaught, unspecified "error" event. (The download of Lekko Half Speed.zip was interrupted)
    at PulseDownloadItem.emit (events.js:166:17)
    at DownloadItem.item.on (/Applications/pulse.app/Contents/Resources/app.asar/src/download1/electron-download-manager/index2.ts:254:22)
    at emitTwo (events.js:106:13)
    at DownloadItem.emit (events.js:194:7)
```

**Comment by fasterthanlime** [comment]
Hi, not sure how you ended up here, but that's not a report for the itch app at all!
