### ISSUE TITLE
🏁 Feedback v37.0.1

### ISSUE THREAD

**Issue by bartasas** [itchio/itch#2344]
Event log:

```
Error: Uncaught, unspecified "error" event. (The download of The Halfling Library.part1.rar was interrupted)
    at PulseDownloadItem.emit (events.js:166:17)
    at DownloadItem.item.on (C:\Users\admin\AppData\Local\pulse\app-37.0.1\resources\app.asar\src\download1\electron-download-manager\index2.ts:254:22)
    at emitTwo (events.js:106:13)
    at DownloadItem.emit (events.js:194:7)
```

**Comment by fasterthanlime** [comment]
This is not a report generated by https://itch.io/app - can you let me know which app you were using so that I can contact the developer and let them know they should change the issue reporting URL? Thanks!

**Comment by fasterthanlime** [comment]
Found'em
