### ISSUE TITLE
[linux] Crash report for v0.9.3

### ISSUE THREAD

**Issue by Chuckaluphagus** [itchio/itch#240]
Crash log:

```
TypeError: db.find is not a function
    at cache_owned_games (/opt/itch/resources/app.asar/app/stores/game-store.js:41:13)
    at fetch_games (/opt/itch/resources/app.asar/app/stores/game-store.js:129:5)
    at /opt/itch/resources/app.asar/app/stores/store.js:87:12
    at /opt/itch/resources/app.asar/app/dispatcher/app-dispatcher.js:92:11
    at Array.forEach (native)
    at Dispatcher.dispatch (/opt/itch/resources/app.asar/app/dispatcher/app-dispatcher.js:89:36)
    at EventEmitter.<anonymous> (/opt/itch/resources/app.asar/app/dispatcher/app-dispatcher.js:103:10)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/opt/itch/resources/atom.asar/browser/api/lib/web-contents.js:85:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by fasterthanlime** [comment]
Hey @Chuckaluphagus, thanks for the report!

0.9.3 is really old, can you try upgrading to 0.11.0 and seeing if you still experience the error? thanks!

**Comment by Chuckaluphagus** [comment]
Hello Amos,

```
My apologies, I was being particularly dim this evening and didn't even
```

realize how old the version must have been.  I downloaded the current
client, and that's working with no problems at all.

Charles
(Chuckaluphagus)

**Comment by fasterthanlime** [comment]
> My apologies, I was being particularly dim this evening and didn't even
> realize how old the version must have been.  I downloaded the current
> client, and that's working with no problems at all.

no need to apologize! versions are moving fast, I don't expect everyone to keep up :) Just wanted to make sure it was still an issue in the latest version before investigating properly.

**Comment by fasterthanlime** [comment]
By the way, we have Deb & RPM repositories now, it should help staying
up-to-date!
