### ISSUE TITLE
🐧 Feedback v25.4.0

### ISSUE THREAD

**Issue by mgerhardy** [itchio/itch#2431]
Event log:

```
TypeError: Cannot read property 'native' of undefined
    at BrowserWindow.nativeWindow.on (/home/mgerhardy/.itch/app-25.4.0/resources/app.asar/dist/main/main.bundle.js:4772:48)
    at emitOne (events.js:116:13)
    at BrowserWindow.emit (events.js:211:7)
```

**Comment by thejpster** [comment]
I see this too
