### ISSUE TITLE
"Could not validate version 15.20.0 of butler" error during first run

### ISSUE THREAD

**Issue by wjurkowlaniec** [itchio/itch#2497]
Crash log:
`TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\jurkwo\AppData\Local\itch\app-25.4.1\resources\app\dist\main\main.bundle.js:41557:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

**Comment by leafo** [comment]
Please update to 26.6.0 or later
