### ISSUE TITLE
🏁 Feedback v25.4.1

### ISSUE THREAD

**Issue by tuttifruiti220** [itchio/itch#2527]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\charm\AppData\Local\itch\app-25.4.1\resources\app\dist\main\main.bundle.js:41557:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by leafo** [comment]
Are you using any virus or security software on your computer?

This error suggests that a process that the itch app tried to start was unable to start, likely related to it being blocked by the system.
