### ISSUE TITLE
🏁 Feedback v25.4.1

### ISSUE THREAD

**Issue by HorribleNerd** [itchio/itch#2536]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\HorribleNerd\AppData\Local\itch\app-25.4.1\resources\app\dist\main\main.bundle.js:41557:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by HorribleNerd** [comment]
Fixed by temporarily turning of antivirus, never had any troubles with it before though.
