### ISSUE TITLE
Games crash on start, claiming I don't own them

### ISSUE THREAD

**Issue by laserburn** [itchio/itch#2544]
I've reported this several times through the bug reporting tool, but I've never seen it acknowledged as a problem. Some other people on the net were reporting this since since early summer.

Games that I've bough in Racial Justice and Equality bundle have worked fine, but then suddenly they wouldn't work any more, claiming that Idon't own them. Games I've downloaded earlier all work fine. 

> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

November 15, 2020, 17:15:23 [INFO] itch 25.4.1 launching 'Lenna's Inception' (#815)
November 15, 2020, 17:15:23 [DEBUG] Locking (/home/nikola/.config/itch/apps/lennas-inception/.itch/runlock.json) for Launch
November 15, 2020, 17:15:23 [INFO] → Launching Lenna's Inception - https://tccoxon.itch.io/lennas-inception
November 15, 2020, 17:15:23 [INFO]    (/home/nikola/.config/itch/apps/lennas-inception) is our install folder
November 15, 2020, 17:15:23 [DEBUG] No license agreement, continuing
November 15, 2020, 17:15:23 [DEBUG] Native platform: 64-bit Linux (native)
November 15, 2020, 17:15:23 [DEBUG] Looking for wine...
November 15, 2020, 17:15:23 [DEBUG] While looking for wine: exec: "wine": executable file not found in $PATH
November 15, 2020, 17:15:24 [WARN] Could not refresh upload: itch.io API error (400): /uploads/430649: you must buy this game to download
November 15, 2020, 17:15:24 [INFO] Passed:
November 15, 2020, 17:15:24 [INFO]   ☁ Linux 64-bit :: 172.31 MiB :: #430649
November 15, 2020, 17:15:24 [INFO]     Executable :: Linux all
November 15, 2020, 17:15:24 [INFO]     Build 36 for channel (linux-amd64-stable) :: 1.1.4 :: #307481
November 15, 2020, 17:15:24 [INFO] • Not filtering, by request
November 15, 2020, 17:15:24 [INFO] ✓ Configured in 148.329694ms
November 15, 2020, 17:15:24 [INFO] • Seeking launch targets for host (64-bit Linux (native))
November 15, 2020, 17:15:24 [INFO] No app manifest.
November 15, 2020, 17:15:24 [INFO] Filtering verdict for host 64-bit Linux (native)
November 15, 2020, 17:15:24 [DEBUG] Filtering 19 candidates to os (linux), arch (amd64)
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/java) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/jjs) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/keytool) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/orbd) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/pack200) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/policytool) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/rmid) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/rmiregistry) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/servertool) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/tnameserv) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/bin/unpack200) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/lib/amd64/libsunec.so_DISABLED) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/lib/ext/nashorn.jar) flavor jar
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/lib/ext/zipfs.jar) flavor jar
November 15, 2020, 17:15:24 [DEBUG] Reviewing (jre/lib/jexec) flavor linux
November 15, 2020, 17:15:24 [DEBUG] Reviewing (lennasinception) flavor script
November 15, 2020, 17:15:24 [DEBUG] Reviewing (lib/jogamp-fat.jar) flavor jar
November 15, 2020, 17:15:24 [DEBUG] Reviewing (lib/libloader.jar) flavor jar
November 15, 2020, 17:15:24 [DEBUG] Reviewing (lib/unirest-java-1.3.10-with-deps.jar) flavor jar
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/java) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/jjs) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/keytool) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/orbd) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/pack200) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/policytool) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/rmid) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/rmiregistry) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/servertool) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/tnameserv) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/bin/unpack200) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/lib/amd64/libsunec.so_DISABLED) - depth 4 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/lib/ext/nashorn.jar) - depth 4 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/lib/ext/zipfs.jar) - depth 4 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (jre/lib/jexec) - depth 3 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (lib/jogamp-fat.jar) - depth 2 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (lib/libloader.jar) - depth 2 > lowest depth 1
November 15, 2020, 17:15:24 [DEBUG] Excluding (lib/unirest-java-1.3.10-with-deps.jar) - depth 2 > lowest depth 1
November 15, 2020, 17:15:24 [INFO] Single target, picking it:
November 15, 2020, 17:15:24 [INFO] | (/home/nikola/.config/itch/apps/lennas-inception/lennasinception) (native)
|-- 1.18 KiB lennasinception script- sh(interpreter=/bin/bash)
|-- ↗ Will be launched as a native application
November 15, 2020, 17:15:24 [INFO] → Using strategy (native)
November 15, 2020, 17:15:24 [INFO]   target (/home/nikola/.config/itch/apps/lennas-inception/lennasinception)
November 15, 2020, 17:15:24 [INFO]   host (64-bit Linux (native))
November 15, 2020, 17:15:24 [INFO] No manifest, no prereqs
November 15, 2020, 17:15:24 [INFO] Giving app temp dir (/home/nikola/.config/itch/apps/lennas-inception/.itch/temp)
November 15, 2020, 17:15:24 [INFO] Environment variables passed: TEMP, TMP
November 15, 2020, 17:15:24 [INFO] Now running!
November 15, 2020, 17:15:31 [INFO] Exited!
November 15, 2020, 17:15:31 [WARN] Exit code 0x1 (1) for (lennasinception)
November 15, 2020, 17:15:31 [ERROR] Had error: Exit code 0x1 (1) for (lennasinception)
November 15, 2020, 17:15:31 [ERROR] → Standard error ================
November 15, 2020, 17:15:31 [ERROR]   java.lang.NoClassDefFoundError: com/codedisaster/steamworks/SteamFriendsCallback
November 15, 2020, 17:15:31 [ERROR]   	at java.lang.Class.forName0(Native Method)
November 15, 2020, 17:15:31 [ERROR]   	at java.lang.Class.forName(Class.java:264)
November 15, 2020, 17:15:31 [ERROR]   	at platform.PlatformAPI.createSteamAPI(PlatformAPI.java:45)
November 15, 2020, 17:15:31 [ERROR]   	at platform.PlatformAPI.createAPI(PlatformAPI.java:33)
November 15, 2020, 17:15:31 [ERROR]   	at platform.PlatformAPI.init(PlatformAPI.java:19)
November 15, 2020, 17:15:31 [ERROR]   	at net.bytten.inceptus.frontend.Main.main(Main.java:170)
November 15, 2020, 17:15:31 [ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
November 15, 2020, 17:15:31 [ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
November 15, 2020, 17:15:31 [ERROR]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
November 15, 2020, 17:15:31 [ERROR]   	at java.lang.reflect.Method.invoke(Method.java:498)
November 15, 2020, 17:15:31 [ERROR]   	at libloader.LoaderTarget.main(LoaderTarget.java:81)
November 15, 2020, 17:15:31 [ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
November 15, 2020, 17:15:31 [ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
November 15, 2020, 17:15:31 [ERROR]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
November 15, 2020, 17:15:31 [ERROR]   	at java.lang.reflect.Method.invoke(Method.java:498)
November 15, 2020, 17:15:31 [ERROR]   	at libloader.LoaderMain.main(LoaderMain.java:70)
November 15, 2020, 17:15:31 [ERROR]   Caused by: java.lang.ClassNotFoundException: com.codedisaster.steamworks.SteamFriendsCallback
November 15, 2020, 17:15:31 [ERROR]   	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
November 15, 2020, 17:15:31 [ERROR]   	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
November 15, 2020, 17:15:31 [ERROR]   	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
November 15, 2020, 17:15:31 [ERROR]   	... 16 more
November 15, 2020, 17:15:31 [ERROR]   X Error of failed request:  BadMatch (invalid parameter attributes)
November 15, 2020, 17:15:31 [ERROR]     Major opcode of failed request:  1 (X_CreateWindow)
November 15, 2020, 17:15:31 [ERROR]     Serial number of failed request:  1549
November 15, 2020, 17:15:31 [ERROR]     Current serial number in output stream:  1551
November 15, 2020, 17:15:31 [ERROR] =================================
November 15, 2020, 17:15:31 [ERROR] → Standard output ===============
November 15, 2020, 17:15:31 [ERROR]   sun.java2d.d3d=(null)
November 15, 2020, 17:15:31 [ERROR]   sun.java2d.noddraw=(null)
November 15, 2020, 17:15:31 [ERROR]   isFullScreenSupported=true
November 15, 2020, 17:15:31 [ERROR]   
November 15, 2020, 17:15:31 [ERROR]   Initializing in standalone mode
November 15, 2020, 17:15:31 [ERROR]   OpenGL pipeline enabled for default config on screen 0
November 15, 2020, 17:15:31 [ERROR]   Reloading assets
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.frontend.tiles.TilesheetRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.frontend.sprites.SpritesheetRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.frontend.text.BitmapFontRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.item.LibraryBookRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.frontend.sound.SoundConfigRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.frontend.sound.MusicConfigRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.item.ItemRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.model.block.BlockRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.model.block.BlockKindRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.generator.BiomeRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.generator.GameGeneratorRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.generator.SpawnerRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.item.DropPoolRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.generator.overworld.GroveRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.player.PhoneContactRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.generator.dungeon.DungeonRoomRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.generator.dungeon.SokobanRoomRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.generator.overworld.importantobjs.OptionalObjectRegistry
November 15, 2020, 17:15:31 [ERROR]   Initializing net.bytten.inceptus.generator.overworld.importantobjs.CityObjectRegistry
November 15, 2020, 17:15:31 [ERROR]   Available GL profiles:
November 15, 2020, 17:15:31 [ERROR]    - GL4bc
November 15, 2020, 17:15:31 [ERROR]    - GL3bc
November 15, 2020, 17:15:31 [ERROR]    - GL2
November 15, 2020, 17:15:31 [ERROR]    - GL4
November 15, 2020, 17:15:31 [ERROR]    - GL3
November 15, 2020, 17:15:31 [ERROR]    - GLES3
November 15, 2020, 17:15:31 [ERROR]    - GL4ES3
November 15, 2020, 17:15:31 [ERROR]    - GL2GL3
November 15, 2020, 17:15:31 [ERROR]    - GLES2
November 15, 2020, 17:15:31 [ERROR]    - GL2ES2
November 15, 2020, 17:15:31 [ERROR]    - GLES1
November 15, 2020, 17:15:31 [ERROR]    - GL2ES1
November 15, 2020, 17:15:31 [ERROR]   Selected GL4bc
November 15, 2020, 17:15:31 [ERROR] =================================
November 15, 2020, 17:15:31 [ERROR] Relaying launch failure.
November 15, 2020, 17:15:31 [DEBUG] rm -rf /home/nikola/.config/itch/apps/lennas-inception/.itch/temp
November 15, 2020, 17:15:31 [DEBUG] Launch cancelled while updating session regularly, bailing out



Error stack:
Exit code 0x1 (1) for (lennasinception)
github.com/itchio/butler/endpoints/launch/launchers/native.(*Launcher).Do.func1
	/builds/itchio/butler/endpoints/launch/launchers/native/native.go:259
github.com/itchio/butler/endpoints/launch/launchers/native.(*Launcher).Do
	/builds/itchio/butler/endpoints/launch/launchers/native/native.go:264
github.com/itchio/butler/endpoints/launch.Launch.func1
	/builds/itchio/butler/endpoints/launch/launch.go:273
github.com/itchio/butler/endpoints/launch.withInstallFolderLock
	/builds/itchio/butler/endpoints/launch/with_install_folder_lock.go:80
github.com/itchio/butler/endpoints/launch.Launch
	/builds/itchio/butler/endpoints/launch/launch.go:35
github.com/itchio/butler/butlerd/messages.(*LaunchType).Register.func1
	/builds/itchio/butler/butlerd/messages/messages.go:2866
github.com/itchio/butler/butlerd.(*Router).HandleRequest.func2
	/builds/itchio/butler/butlerd/router.go:306
github.com/itchio/butler/butlerd.(*Router).HandleRequest
	/builds/itchio/butler/butlerd/router.go:315
github.com/itchio/butler/butlerd.(*gatedHandler).HandleRequest
	/builds/itchio/butler/butlerd/butlerd.go:159
github.com/itchio/butler/butlerd/jsonrpc2.(*connImpl).handleIncomingMessage.func1
	/builds/itchio/butler/butlerd/jsonrpc2/jsonrpc2.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373

**Comment by leafo** [comment]
This particular error looks like the game is just crashing, I don't see anything errors from us that would suggest you don't own the game in the logs you provided.

**Comment by laserburn** [comment]
The line with "Could not refresh upload: itch.io API error (400)..." message is shown in yellow, suggesting it's important. It's the same error whatever game I start, I can actually see the game window for a brief moment, then the crash window appears. 

The games that I've installed earlier, like Depth of Extinction or Overland still start perfectly normal, but the games I installed later all crash in the same way. If I would install another game now, it would also crash like this.

**Comment by valrus** [comment]
I have the same issue, with the same message in yellow. The game works fine if I "show in Finder" and launch with a normal double click.

**Comment by leafo** [comment]
Closing out super old issues. Please post a comment if you are still having trouble when running on the newest version of the app.

Thanks
