### ISSUE TITLE
🐧 Feedback v25.4.1

### ISSUE THREAD

**Issue by cowboysmall** [itchio/itch#2545]
Itch app crashed after starting up - after update check had completed. Running on Fedora 33.

Event log:

```
TypeError: Cannot read property 'native' of undefined
    at BrowserWindow.<anonymous> (/home/jerry/.itch/app-25.4.1/resources/app/dist/main/main.bundle.js:5465:48)
    at BrowserWindow.emit (events.js:310:20)
```

**Comment by cowboysmall** [comment]
I should have checked to see if this issue had already been reported - it seems it has been reported. My apologies.
