### ISSUE TITLE
🏁 Feedback v25.4.1

### ISSUE THREAD

**Issue by Phantom-Storm** [itchio/itch#2587]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\ngans\AppData\Local\itch\app-25.4.1\resources\app\dist\main\main.bundle.js:41557:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by DraziaXardei** [comment]
I followed steps from here and was able to fix my problem.
https://itch.io/docs/itch/installing/windows.html#antivirus-software

You pretty much just need to exclude very specific folders from your antivirus.

/C:Users/(Comp Name)/AppData/Roaming/Itch/Broth
and
/C:Users/(Comp Name)/AppData/Local/Itch

Just exclude the whole folders.

I know I only excluded two folders, even though it says to exclude three, but I found it works with just the two folders.
I couldn't even find a:
/C:Users/(Comp Name)/AppData/Roaming/Itch/Prereqs
But if you do, I'd suggest you exclude it too as the page says.

Hopefully this helps anyone.

**Comment by leafo** [comment]
Please update to 26.6.0 or later
