### ISSUE TITLE
🏁 Feedback v25.4.1 this error has been going on for over a year

### ISSUE THREAD

**Issue by Callabrimdoor** [itchio/itch#2589]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (G:\Itch.io\app-25.4.1\resources\app\dist\main\main.bundle.js:41557:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by Callabrimdoor** [comment]
I have reinstalled multiple times without success, and searched for help with no success. (I apologize for not adding this the first time) Throughout those multiple times it has been unable to get past the last part of an update 

> I followed steps from here and was able to fix my problem.
> https://itch.io/docs/itch/installing/windows.html#antivirus-software
> 
> You pretty much just need to exclude very specific folders from your antivirus.
> 
> /C:Users/(Comp Name)/AppData/Roaming/Itch/Broth
> and
> /C:Users/(Comp Name)/AppData/Local/Itch
> 
> Just exclude the whole folders.
> 
> I know I only excluded two folders, even though it says to exclude three, but I found it works with just the two folders.
> I couldn't even find a:
> /C:Users/(Comp Name)/AppData/Roaming/Itch/Prereqs
> But if you do, I'd suggest you exclude it too as the page says.
> 
> Hopefully this helps anyone.

I thank you greatly for giving out the solution, it took some time to figure out how to do. I'm I'm finally able to use Itch.io again. A little irked at how simple the issue was, but happy all the same. Thank you and have a good day!

**Comment by DraziaXardei** [comment]
I followed steps from here and was able to fix my problem.
https://itch.io/docs/itch/installing/windows.html#antivirus-software

You pretty much just need to exclude very specific folders from your antivirus.

/C:Users/(Comp Name)/AppData/Roaming/Itch/Broth
and
/C:Users/(Comp Name)/AppData/Local/Itch

Just exclude the whole folders.

I know I only excluded two folders, even though it says to exclude three, but I found it works with just the two folders.
I couldn't even find a:
/C:Users/(Comp Name)/AppData/Roaming/Itch/Prereqs
But if you do, I'd suggest you exclude it too as the page says.

Hopefully this helps anyone.

**Comment by leafo** [comment]
Please update to 26.6.0 or later
