### ISSUE TITLE
🏁 Feedback v25.4.1

### ISSUE THREAD

**Issue by Arisda** [itchio/itch#2593]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\user\AppData\Local\itch\app-25.4.1\resources\app\dist\main\main.bundle.js:41557:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Bruh, I did the thing with the Anti-Virus, and didn't work, what I'm supposed to do now?

**Comment by leafo** [comment]
> Bruh, I did the thing with the Anti-Virus, and didn't work, what I'm supposed to do now?

Can you tell us what "thing" you did? If you didn't fully disable it then you're going to still run into the issue. I don't recommend trying to add an "exception" since that's easy to do wrong, or may not even work due ot the nature of how the app boots games.

**Comment by leafo** [comment]
Please update to 26.6.0 or later
