### ISSUE TITLE
🏁 Feedback v25.4.1

### ISSUE THREAD

**Issue by Koto2081** [itchio/itch#2604]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\jonat\AppData\Local\itch\app-25.4.1\resources\app\dist\main\main.bundle.js:41557:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by Koto2081** [comment]
The installation doesnt want to finish and ask me to send this 
What do i do ?

**Comment by leafo** [comment]
Please update to 26.6.0 or later
