### ISSUE TITLE
Cant open Itch anymore

### ISSUE THREAD

**Issue by eduardomunhozr** [itchio/itch#2619]
I had just installed it, it was working fine till I pressed to suggest translations for portuguese and the program just crashed, now everytime I try to open it, it's just this black screen, even tried re-installing it and nothing seems to solve it

![Sem título](https://user-images.githubusercontent.com/76234597/116592907-ec9c0080-a8f6-11eb-820f-21030f894a0b.png)

**Comment by Lucas8x** [comment]
²

**Comment by geekley** [comment]
Got the same issue when switching to Portuguese in preferences (both `Português (Brazil)` and `Português`). I'm on Linux using the flathub version of the app. Switching gives blank screen and I can't see anything on the UI, even the preferences window to switch back is blank.

I got it to work again by manually editing `preferences.json`, so `lang` is back to `en` instead of `pt_BR`, then quitting in the systray and restarting the app. It's in itch app installation folder (in my case, `~/.var/app/io.itch.itch/config/itch/`).

Find this at the end, for example:
```jsonc
"lang":"pt_BR"
```
And change to this to make it in English and fix it for now:
```jsonc
"lang":"en"
```

**Comment by geekley** [comment]
@leafo This is a major bug that makes the app unusable!

It's probably related to the locale having an underscore for `pt_BR` and `pt_PT`, since it doesn't seem to happen for any other language (even Chinese is just `zh` so it works).

When switching, the console logs this error:
```
react-dom.production.min.js:209 RangeError: Incorrect locale information provided
    at Function.supportedLocalesOf (<anonymous>)
    at createIntl (create-intl.js:43:1)
    at provider_createIntl (provider.js:62:20)
    at new IntlProvider (provider.js:81:19)
    at Lg (react-dom.production.min.js:134:169)
    at fi (react-dom.production.min.js:176:66)
    at Rj (react-dom.production.min.js:263:420)
    at Qj (react-dom.production.min.js:246:259)
    at Kj (react-dom.production.min.js:246:191)
    at yj (react-dom.production.min.js:239:172)
Ci @ react-dom.production.min.js:209
Xi.c.callback @ react-dom.production.min.js:226
Cg @ react-dom.production.min.js:131
Ji @ react-dom.production.min.js:212
Sj @ react-dom.production.min.js:255
exports.unstable_runWithPriority @ scheduler.production.min.js:19
cg @ react-dom.production.min.js:122
Jj @ react-dom.production.min.js:248
yj @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
exports.unstable_runWithPriority @ scheduler.production.min.js:19
cg @ react-dom.production.min.js:122
fg @ react-dom.production.min.js:123
gg @ react-dom.production.min.js:122
Mj @ react-dom.production.min.js:240
notify @ Subscription.js:19
notifyNestedSubs @ Subscription.js:90
handleChangeWrapper @ Subscription.js:95
dispatch @ redux.js:222
(anonymous) @ syncRenderer.js:33
dispatch @ redux.js:638
(anonymous) @ preload.js:39
emit @ VM24 node:events:513
onMessage @ VM131 renderer_init:2

preload.js:39 Uncaught Error: Incorrect locale information provided
    at EventEmitter.<anonymous> (preload.js:39:1)
    at EventEmitter.emit (VM24 node:events:513:28)
    at Object.onMessage (VM131 renderer_init:2:9151)
(anonymous)	@	preload.js:39
emit	@	VM24 node:events:513
onMessage	@	VM131 renderer_init:2
```
I even tried editing preferences.json to use dash to see if it works like `pt-BR` but no luck.
