### ISSUE TITLE
🐧 Feedback v25.5.1

### ISSUE THREAD

**Issue by adamdmoss** [itchio/itch#2653]
Event log:

```
TypeError: Cannot read property 'native' of undefined
    at BrowserWindow.<anonymous> (/zfs2/home/adam/.itch/app-25.5.1/resources/app/dist/main/main.bundle.js:6854:48)
    at BrowserWindow.emit (events.js:310:20)
```
(while quitting)

**Comment by adamdmoss** [comment]
dupe of #2649
