### ISSUE TITLE
🏁 Feedback v25.5.1

### ISSUE THREAD

**Issue by siatsoft** [itchio/itch#2669]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (E:\Program Files\Itch\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by siatsoft** [comment]
Unfortunately cannot complete installation of app as I keep getting the above error even with antivirus / firewall temporarily disabled.

**Comment by leafo** [comment]
Please update to 26.6.0 or later
