### ISSUE TITLE
25.5.1 Most views won't open; butler error

### ISSUE THREAD

**Issue by 2139-40** [itchio/itch#2718]
On macOS 10.14.6, running on a MacBook Pro with an Intel chipset.

The app launches, but most features don't work. The itch menu bar is visible, but no windows are opened on launch. The only item in the View menu is 'Downloads' (and to be fair, the Downloads window does open and successfully downloads updates to games I already have installed). The Account menu only has 'Change User...'; I don't know if there's supposed to be anything else there.

Explore, Library, and Collections show up in the context menu for the dock icon, but selecting them doesn't do anything. Preferences does open. The 'recent games' item in the dock context menu also work—there are a few games listed there from a while back before the app broke—but it's impossibly to launch anything else.

There's a set of errors in the application log that may be related:

{"time":1632285423965,"level":50,"msg":"Caught butler error:","name":"mcall"}
{"time":1632285423965,"level":50,"msg":"butler version: undefined","name":"mcall"}
{"time":1632285423965,"level":50,"msg":"Golang stack:\nError\n    at Function.fromInternalCode (/Users/fmac/Applications/itch.app/Contents/Resources/app/dist/main/main.bundle.js:459:24)\n    at Conversation.cancel (/Users/fmac/Applications/itch.app/Contents/Resources/app/dist/main/main.bundle.js:27485:47)\n    at Conversation.close (/Users/fmac/Applications/itch.app/Contents/Resources/app/dist/main/main.bundle.js:27494:14)\n    at Socket.<anonymous> (/Users/fmac/Applications/itch.app/Contents/Resources/app/dist/main/main.bundle.js:27309:22)\n    at Socket.emit (events.js:310:20)\n    at TCP.<anonymous> (net.js:672:12)","name":"mcall"}

**Comment by leafo** [comment]
Closing out stale issues. If you are still having issues with the most recent version of the app feel free to leave a comment.

Thanks
