### ISSUE TITLE
🏁 Feedback v25.5.1

### ISSUE THREAD

**Issue by Dylanrage** [itchio/itch#2756]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (D:\Epic Games\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by vezza** [comment]
Not starting on Fedora 35 x86_64

**Comment by jpsnyder** [comment]
Can confirm it doesn't work on Fedora 35. On startup I get a blank gray box for 2 seconds and then crashes.

**Comment by matdave** [comment]
another bump on this

**Comment by leafo** [comment]
Please update to 26.6.0 or later
