### ISSUE TITLE
🏁 Feedback v25.5.1 FIXED (sort of)

### ISSUE THREAD

**Issue by Kakkahiukkanen** [itchio/itch#2769]
This was my issue as with many others:

Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Program Files\Itch\Itch\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

This is a bit of hacky fix, I solved this issue by opening the main.bundle.js in notepad++, then removing these two functions:

<img width="542" alt="fix1" src="https://user-images.githubusercontent.com/87758952/154754595-46889460-988e-40d5-8add-ba595192ddd3.PNG">

<img width="482" alt="fix2" src="https://user-images.githubusercontent.com/87758952/154754918-cae1adcd-4908-4aec-834d-2fc8513dd54f.PNG">

So far the app works fine.
As far as I can tell, all this means is that the app will not automatically remove old versions of itself, when updating. I could be wrong though but we'll see when the next update comes.

**Comment by Kakkahiukkanen** [comment]
I don't know if this is useful, but there are also these error messages. I looked into the butler/versions folder and it was empty . Not sure if it's supposed to be empty, maybe that's why it can't validate version 15.21.0 since it's not there.

<img width="700" alt="Error" src="https://user-images.githubusercontent.com/87758952/154752190-4ea48e7d-928d-4452-91c8-1a036ce7dfc5.PNG">
<img width="721" alt="Error2" src="https://user-images.githubusercontent.com/87758952/154752192-a6998d08-7162-43e8-9279-4124d0c5c015.PNG">

**Comment by corey-martin** [comment]
Thanks for the tip! confirmed this worked for me too (had to End Task on several instances of "the itch.io desktop app" from previous failures)

**Comment by leafo** [comment]
This error is typically associated third party virus or security scanner tampering with your system without your permission. Our understanding is why you are seeing a missing butler executable is because it's being deleted unprompted by your security software.

**Comment by Sangrel** [comment]
> This was my issue as with many others:
> 
> Event log:
> 
> ```
> TypeError: Cannot read property 'pid' of undefined
>     at Timeout._onTimeout (C:\Program Files\Itch\Itch\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
>     at listOnTimeout (internal/timers.js:549:17)
>     at processTimers (internal/timers.js:492:7)
> ```
> 
> This is a bit of hacky fix, I solved this issue by opening the main.bundle.js in notepad++, then removing these two functions:
> 
> <img alt="fix1" width="542" src="https://user-images.githubusercontent.com/87758952/154754595-46889460-988e-40d5-8add-ba595192ddd3.PNG">
> 
> <img alt="fix2" width="482" src="https://user-images.githubusercontent.com/87758952/154754918-cae1adcd-4908-4aec-834d-2fc8513dd54f.PNG">
> 
> So far the app works fine. As far as I can tell, all this means is that the app will not automatically remove old versions of itself, when updating. I could be wrong though but we'll see when the next update comes.

Ty its help

**Comment by leafo** [comment]
Please update to 26.6.0 or later
