### ISSUE TITLE
🏁 Feedback v25.5.1

### ISSUE THREAD

**Issue by PieterHorstman** [itchio/itch#2782]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\piete\AppData\Local\itch\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by corey-martin** [comment]
same

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Program Files\itch\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by corey-martin** [comment]
hacky fix from #2769 worked for me

**Comment by leafo** [comment]
Please update to 26.6.0 or later
