### ISSUE TITLE
🏁 Feedback v25.5.1

### ISSUE THREAD

**Issue by Irene2081** [itchio/itch#2785]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\irene\AppData\Local\itch\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
I was trying to install the app but it keeps saying it can't validate version 15.21.0 of butler, seems like the folder that should contain it is empty though. Any thoughts on how to fix this?

**Comment by leafo** [comment]
Please update to 26.6.0 or later
