### ISSUE TITLE
🏁 Failing to install v25.5.1

### ISSUE THREAD

**Issue by TheBunyip** [itchio/itch#2801]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\BenMiller\AppData\Local\itch\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by TheBunyip** [comment]
Error when trying to install on Windows 10.  This happens if I try to run the latest installer over the top of my existing (but 3 months out of date) installation of the app.  But uninstalling that previous version and then installing the latest one also fails the same way.

**Comment by leafo** [comment]
Please update to 26.6.0 or later
