### ISSUE TITLE
🐧 Feedback v25.5.1

### ISSUE THREAD

**Issue by FiveClawFurry** [itchio/itch#2819]
Itchio app on ubuntu linux (Zorin OS 16.1)

Event log:

```
TypeError: Cannot read property 'native' of undefined
    at BrowserWindow.<anonymous> (/home/darkstar696/.itch/app-25.5.1/resources/app/dist/main/main.bundle.js:6854:48)
    at BrowserWindow.emit (events.js:310:20)
```

**Comment by FiveClawFurry** [comment]
Client crashed on closing the "Check Game Update" window.
