### ISSUE TITLE
🏁 Feedback v25.5.1 - "Crash" before download completion.

### ISSUE THREAD

**Issue by MBfromOK** [itchio/itch#2830]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\Micah\AppData\Local\itch\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
It seems like the installer is reporting the install failed (and that it crashed) while still waiting for the 6 MB download to complete.

**Comment by MBfromOK** [comment]
Additionally the error states that it is unable to validate which version (or a particular version) of Butler is installed... The 4th retry seems to have worked? (I was finally given the login screen)

**Comment by ilyaleb99** [comment]
i can't Install it please fix the issue

**Comment by leafo** [comment]
Please update to 26.6.0 or later
