### ISSUE TITLE
🏁 Feedback v25.5.1

### ISSUE THREAD

**Issue by DT-is-not-available** [itchio/itch#2855]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\dt\AppData\Local\itch\app-25.5.1\resources\app\dist\main\main.bundle.js:38510:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
it automatically opened this page for me when it crashed (right after starting it), so im going to assume all the relevant info is already here.

**Comment by DT-is-not-available** [comment]
actually, scrolling through the open issues, it looks like you guys are already aware of this one, so im going to go ahead and close this
