### ISSUE TITLE
Running into Error: net::ERR_CERT_AUTHORITY_INVALID when Trying to Download Butler

### ISSUE THREAD

**Issue by 4tuw2tuv0** [itchio/itch#2875]
I've put the errors below; I have certificates installed at the usually expected place of `/etc/ssl/certs/ca-certificates.crt`.

```
22:42:39.124 INFO itch@25.5.1 on electron@10.4.5 in production
22:42:39.202 DEBUG (m/net/register-itch-protocol) Registering itch: protocol for session with user agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) itch/25.5.1 Chrome/85.0.4183.121 Electron/10.4.5 Safari/537.36
22:42:39.344 INFO (m/reac/preboot) preboot ran in 147.00ms
22:42:39.346 DEBUG (m/reac/open-at-login) Updating login item settings, open=false, hidden=false
22:42:39.346 DEBUG (m/reac/open-at-login) Copying /usr/share/applications/io.itch.itch.desktop => ~/.config/autostart/io.itch.itch.desktop
22:42:39.351 DEBUG (m/reac/winds) Waiting on root window to dispatch boot
22:42:39.542 INFO (🔧 setup) Setup starting...
22:42:39.554 INFO (🔧 setup) Creating broth manager
22:42:39.555 INFO (🔧 setup) Ensuring broth dependencies, for startup
(node:8410) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
22:42:39.558 DEBUG (🔧 setup) Package (itch) got version prefix
22:42:39.561 INFO (📦 butler) No chosen version, attempting install...
22:42:39.562 DEBUG (📦 butler) Trying to satisfy semver constraint (^15.20.0)
22:42:39.562 DEBUG (📦 butler) GET (https://broth.itch.ovh/butler/linux-amd64/versions)
22:42:39.562 DEBUG (r) HTTP get https://broth.itch.ovh/butler/linux-amd64/versions
22:42:39.565 DEBUG (m/reac/locales) Reading local locale file ~/.itch/app-25.5.1/resources/app/src/static/locales/en.json
22:42:39.571 DEBUG (m/reac/locales) Reading remote locale file ~/.itch/app-25.5.1/resources/app/src/static/locales/en.json
22:42:40.172 WARN (📦 butler) While checking for latest version: Error: net::ERR_CERT_AUTHORITY_INVALID
    at ClientRequest.<anonymous> (~/.itch/app-25.5.1/resources/app/dist/main/main.bundle.js:16347:20)
    at ClientRequest.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
22:42:40.184 DEBUG (📦 butler) Present versions: 
22:42:40.187 ERROR (🔧 setup) setup got error: Error: Could not retrieve latest version of (butler): net::ERR_CERT_AUTHORITY_INVALID
    at package_Package.doUpgrade (~/.itch/app-25.5.1/resources/app/dist/main/main.bundle.js:17361:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async package_Package.upgrade (~/.itch/app-25.5.1/resources/app/dist/main/main.bundle.js:17328:13)
    at async package_Package.ensure (~/.itch/app-25.5.1/resources/app/dist/main/main.bundle.js:17282:9)
    at async manager_Manager.ensure (~/.itch/app-25.5.1/resources/app/dist/main/main.bundle.js:17605:13)
    at async initialSetup (~/.itch/app-25.5.1/resources/app/dist/main/main.bundle.js:17705:9)
    at async ~/.itch/app-25.5.1/resources/app/dist/main/main.bundle.js:17809:9
    at async Promise.all (index 1)
22:42:40.237 INFO (m/reac/i18n) Language settings: preference undefined, sniffed en-US, fallback en
22:42:40.247 DEBUG (m/reac/locales) Reading local locale file ~/.itch/app-25.5.1/resources/app/src/static/locales/en.json
22:42:40.256 DEBUG (m/reac/locales) Reading remote locale file ~/.itch/app-25.5.1/resources/app/src/static/locales/en.json
22:42:42.262 DEBUG (m/reac/locales) Downloading fresh locale file from https://locales.itch.ovh/itch/en.json
22:42:42.262 DEBUG (r) HTTP get https://locales.itch.ovh/itch/en.json
22:42:42.426 WARN (m/reac/locales) Failed downloading locale for en: net::ERR_CERT_AUTHORITY_INVALID
22:43:09.208 INFO (m/reac/updater) Regularly scheduled check for game updates...
22:43:09.210 INFO (m/reac/updater) Scheduling next game update check for Thu Oct 27 2022 18:10:27 GMT-0500 (Central Daylight Time)
 23:05:52.780 DEBUG (m/reac/winds) On window.close: close to tray enabled
```

**Comment by leafo** [comment]
Likely a transient network issue, closing out old tickets.
