### ISSUE TITLE
🏁 Feedback v25.6.2

### ISSUE THREAD

**Issue by queeenyyy** [itchio/itch#2930]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\nyanc\AppData\Local\itch\app-25.6.2\resources\app\dist\main\main.bundle.js:38310:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by leafo** [comment]
Please update to 26.6.0 or later
