### ISSUE TITLE
🏁 Feedback v25.6.2

### ISSUE THREAD

**Issue by Atri7** [itchio/itch#2943]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (J:\Users\Jace\AppData\Local\itch\app-25.6.2\resources\app\dist\main\main.bundle.js:38310:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

I launched the Itch installer, set my directory, clicked Install, then it crashed. It worked fine when I tried to install it a second time, a few minutes later.

Thanks for your hard work!

**Comment by leafo** [comment]
Please update to 26.6.0 or later
