### ISSUE TITLE
🏁 Feedback v25.6.2

### ISSUE THREAD

**Issue by Boopiful** [itchio/itch#2966]
Event log:

```
TypeError: Cannot read property 'pid' of undefined
    at Timeout._onTimeout (C:\Users\olivi\AppData\Local\itch\app-25.6.2\resources\app\dist\main\main.bundle.js:38310:61)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by 3ter** [comment]
Close as obviously not intended to add a valuable issue to the repo.

**Comment by leafo** [comment]
Please update to 26.6.0 or later
