### ISSUE TITLE
Unable to submit crash reports

### ISSUE THREAD

**Issue by fuzxi** [itchio/itch#3067]
When attempting to submit a crash report, the itch client displays the following:

Sorry, we could not send your report.
```
TypeError: Failed to fetch
  at file:///opt/itch/resources/app/dist/renderer/320.chunk.js:1135.40
  at doAsync (file:///opt/itch/resources/app/dist/renderer/402.chunk.js:642.5)
  at ReportIssue.onSend (file:///opt/itch/resources/app/dist/renderer/320.chunk.js:1110:39)
  at Object.ba (file:///opt/itch/resources/app/dist/renderer/renderer.bundle.js:24482:84)
  at ja (file:///opt/itch/resources/app/dist/renderer/renderer.bundle.js:24482:238)
  at ka (file:///opt/itch/resources/app/dist/renderer/renderer.bundle.js:24482:292)
  at oa (file:///opt/itch/resources/app/dist/renderer/renderer.bundle.js:24483:72)
  at lc (file:///opt/itch/resources/app/dist/renderer/renderer.bundle.js:24520:146)
  at jc (file:///opt/itch/resources/app/dist/renderer/renderer.bundle.js:24519:255)
  at mc (file:///opt/itch/resources/app/dist/renderer/renderer.bundle.js:24520:334)
```
Itch version 26.1.9
Butler version 15.21.0
Itch-setup version 1.26.0
Installed via the `itch-bin` AUR package on 64-bit Arch Linux.

Also, in the "Your message" section of the report submission, "Where does my report go?" links to https://dale.itch.zone, which appears to be inaccessible.

**Comment by hsandt** [comment]
Issue still present today with:
itch @ 26.1.9 (no change, so no surprise)
butler @ 15.24.0
itch-setup @ 1.27.0
(btw I had to use an OCR to copy the version from the Preferences Advanced section, would be great to have a "Copy version" button as in other apps)

In bonus, I got a repro: close a Godot game directly with Alt+F4 (may work with games made with other engines too). I could repro with this game for which I never put a pause menu with Exit button and so it was the most efficient way to close it:
https://fluentlystudios.itch.io/flame-of-hope

I got exactly the same issue (just install path changed on Windows), and the dale.itch.zone link also leads to nothing (Unable to connect). If it's normal because it's not meant to be accessed via HTTP get, we may as well remove the hyperlink, just show the domain name.
