### ISSUE TITLE
Setup Error: Could not validate version 15.21.0 of butler

### ISSUE THREAD

**Issue by 4tuw2tuv0** [itchio/itch#3076]
During the setup of launching the program, I encounter the error in the title. The full logs are below:

> 22:54:28.188 INFO itch@26.1.9 on electron@22.3.27 in production
> 22:54:28.270 DEBUG (m/reac/updater) Skipping game update check as requested per environment variable
> [20305:0920/175428.346153:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
> [20305:0920/175428.346174:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
> 22:54:28.374 DEBUG (m/net/register-itch-protocol) Registering itch: protocol for session with user agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) itch/26.1.9 Chrome/108.0.5359.215 Electron/22.3.27 Safari/537.36
> LaunchProcess: failed to execvp:
> xdg-settings
> LaunchProcess: failed to execvp:
> xdg-settings
> 22:54:28.450 INFO (m/reac/preboot) preboot ran in 87.00ms
> 22:54:28.454 DEBUG (m/reac/open-at-login) Updating login item settings, open=false, hidden=false
> 22:54:28.454 DEBUG (m/reac/open-at-login) Copying /usr/share/applications/io.itch.itch.desktop => /home/jaft/.config/io.itch.itch.desktop
> 22:54:28.457 DEBUG (m/reac/winds) Waiting on root window to dispatch boot
> 22:54:29.397 INFO (m/reac/i18n) Language settings: preference undefined, sniffed en-US, fallback en
> 22:54:29.411 DEBUG (m/reac/locales) Reading local locale file /gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/src/static/locales/en.json
> 22:54:29.414 INFO (🔧 setup) Setup starting...
> 22:54:29.416 INFO (🔧 setup) Creating broth manager
> 22:54:29.418 INFO (🔧 setup) Ensuring broth dependencies, for startup
> 22:54:29.420 DEBUG (🔧 setup) Package (itch) got version prefix
> 22:54:29.424 DEBUG (m/reac/locales) Reading remote locale file /gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/src/static/locales/en.json
> 22:54:29.427 INFO (📦 butler) No chosen version, attempting install...
> 22:54:29.429 DEBUG (📦 butler) Trying to satisfy semver constraint (^15.20.0)
> 22:54:29.429 DEBUG (📦 butler) GET (https://broth.itch.zone/butler/linux-amd64/versions)
> 22:54:29.429 DEBUG (r) HTTP get https://broth.itch.zone/butler/linux-amd64/versions
> 22:54:29.435 DEBUG (m/reac/locales) Reading local locale file /gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/src/static/locales/en.json
> 22:54:29.441 DEBUG (m/reac/locales) Reading remote locale file /gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/src/static/locales/en.json
> 22:54:29.896 DEBUG (r) Got HTTP 200, content-length: 0 B
> 22:54:29.910 INFO (📦 butler) Latest is (15.21.0)
> 22:54:29.929 WARN (📦 butler) Sanity check failed: spawn /home/jaft/.config/itch/broth/butler/versions/15.21.0/butler ENOENT
> 22:54:29.944 INFO (📦 butler) Downloading (butler)@(15.21.0)
> 22:54:29.945 INFO (📦 butler) ...from (https://broth.itch.zone/butler/linux-amd64/15.21.0/butler.zip)
> 22:54:29.945 INFO (📦 butler) ...to (/home/jaft/.config/itch/broth/butler/downloads/butler.zip)
> 22:54:29.950 DEBUG (r) HTTP get https://broth.itch.zone/butler/linux-amd64/15.21.0/butler.zip
> 22:54:30.822 DEBUG (r) Got HTTP 200, content-length: 9.4 MiB
> 22:54:30.823 INFO (📦 butler) HTTP 200 https://broth.itch.zone/butler/linux-amd64/15.21.0/butler.zip
> 22:54:31.098 INFO (📦 butler) 100.0% done, eta 0.0s @ 9.4 MiB/s
> 22:54:31.099 DEBUG (📦 butler) Awaiting file sink promise
> 22:54:31.138 INFO (📦 butler) Downloaded 9.4 MiB / 9.4 MiB (9830035 bytes)
> 22:54:31.142 INFO (📦 butler) Download completed.
> 22:54:31.142 INFO (📦 butler) Extracting...
> 22:54:31.156 DEBUG (📦 butler) Total zip entries: 3
> 22:54:31.156 DEBUG (📦 butler) .zip filesize: 9830035
> 22:54:31.161 DEBUG (📦 butler) → 7z.so
> 22:54:31.167 INFO (📦 butler) Extracting /home/jaft/.config/itch/broth/butler/versions/15.21.0/7z.so
> (node:20305) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use `itch --trace-deprecation ...` to show where the warning was created)
> 22:54:31.425 DEBUG (📦 butler) → butler
> 22:54:31.425 INFO (📦 butler) Extracting /home/jaft/.config/itch/broth/butler/versions/15.21.0/butler
> 22:54:31.444 DEBUG (m/reac/locales) Downloading fresh locale file from https://locales.itch.zone/itch/en.json
> 22:54:31.444 DEBUG (r) HTTP get https://locales.itch.zone/itch/en.json
> 22:54:31.482 WARN (m/reac/locales) Failed downloading locale for en: net::ERR_NAME_NOT_RESOLVED
> 22:54:31.982 DEBUG (📦 butler) → libc7zip.so
> 22:54:31.983 INFO (📦 butler) Extracting /home/jaft/.config/itch/broth/butler/versions/15.21.0/libc7zip.so
> 22:54:31.989 INFO (📦 butler) Validating...
> 22:54:31.999 WARN (📦 butler) Sanity check failed: spawn /home/jaft/.config/itch/broth/butler/versions/15.21.0/butler ENOENT
> 22:54:32.008 DEBUG (📦 butler) Present versions: 15.21.0
> 22:54:32.008 INFO (📦 butler) Removing obsolete version (15.21.0)
> 22:54:32.021 ERROR (🔧 setup) setup got error: Error: Could not validate version 15.21.0 of butler
>     at Package.doUpgrade (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18339:23)
>     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Package.upgrade (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18262:13)
>     at async Package.ensure (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18216:9)
>     at async Manager.ensure (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18593:13)
>     at async initialSetup (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18681:9)
>     at async /gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18785:9
>     at async Promise.all (index 1)
> (node:20305) [DEP0003] DeprecationWarning: _writableState.buffer is deprecated. Use _writableState.getBuffer instead.
> [20355:0920/175538.129271:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
> [20355:0920/180102.186399:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
> [20355:0920/180102.189969:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
> 23:01:02.796 INFO (🔧 setup) Setup starting...
> 23:01:02.797 INFO (🔧 setup) Ensuring broth dependencies, for startup
> 23:01:02.799 DEBUG (🔧 setup) Package (itch) got version prefix
> 23:01:02.799 INFO (📦 butler) No chosen version, attempting install...
> 23:01:02.800 DEBUG (📦 butler) Trying to satisfy semver constraint (^15.20.0)
> 23:01:02.801 DEBUG (📦 butler) GET (https://broth.itch.zone/butler/linux-amd64/versions)
> 23:01:02.801 DEBUG (r) HTTP get https://broth.itch.zone/butler/linux-amd64/versions
> 23:01:03.133 DEBUG (r) Got HTTP 200, content-length: 0 B
> 23:01:03.143 INFO (📦 butler) Latest is (15.21.0)
> 23:01:03.175 WARN (📦 butler) Sanity check failed: spawn /home/jaft/.config/itch/broth/butler/versions/15.21.0/butler ENOENT
> 23:01:03.181 INFO (📦 butler) Downloading (butler)@(15.21.0)
> 23:01:03.181 INFO (📦 butler) ...from (https://broth.itch.zone/butler/linux-amd64/15.21.0/butler.zip)
> 23:01:03.182 INFO (📦 butler) ...to (/home/jaft/.config/itch/broth/butler/downloads/butler.zip)
> 23:01:03.187 DEBUG (r) HTTP get https://broth.itch.zone/butler/linux-amd64/15.21.0/butler.zip
> 23:01:03.939 DEBUG (r) Got HTTP 200, content-length: 9.4 MiB
> 23:01:03.940 INFO (📦 butler) HTTP 200 https://broth.itch.zone/butler/linux-amd64/15.21.0/butler.zip
> 23:01:04.238 INFO (📦 butler) 100.0% done, eta 0.0s @ 9.4 MiB/s
> 23:01:04.239 DEBUG (📦 butler) Awaiting file sink promise
> 23:01:04.241 INFO (📦 butler) Downloaded 9.4 MiB / 9.4 MiB (9830035 bytes)
> 23:01:04.244 INFO (📦 butler) Download completed.
> 23:01:04.245 INFO (📦 butler) Extracting...
> 23:01:04.264 DEBUG (📦 butler) Total zip entries: 3
> 23:01:04.268 DEBUG (📦 butler) .zip filesize: 9830035
> 23:01:04.277 DEBUG (📦 butler) → 7z.so
> 23:01:04.285 INFO (📦 butler) Extracting /home/jaft/.config/itch/broth/butler/versions/15.21.0/7z.so
> 23:01:04.364 DEBUG (📦 butler) → butler
> 23:01:04.365 INFO (📦 butler) Extracting /home/jaft/.config/itch/broth/butler/versions/15.21.0/butler
> 23:01:04.855 DEBUG (📦 butler) → libc7zip.so
> 23:01:04.856 INFO (📦 butler) Extracting /home/jaft/.config/itch/broth/butler/versions/15.21.0/libc7zip.so
> 23:01:04.861 INFO (📦 butler) Validating...
> 23:01:04.871 WARN (📦 butler) Sanity check failed: spawn /home/jaft/.config/itch/broth/butler/versions/15.21.0/butler ENOENT
> 23:01:04.876 DEBUG (📦 butler) Present versions: 15.21.0
> 23:01:04.876 INFO (📦 butler) Removing obsolete version (15.21.0)
> 23:01:04.884 ERROR (🔧 setup) setup got error: Error: Could not validate version 15.21.0 of butler
>     at Package.doUpgrade (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18339:23)
>     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Package.upgrade (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18262:13)
>     at async Package.ensure (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18216:9)
>     at async Manager.ensure (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18593:13)
>     at async initialSetup (/gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18681:9)
>     at async /gnu/store/hbjgm81vw3varrgfyci3jhgi59mmg3n3-itch-26.1.9/resources/app/dist/main/main.bundle.js:18788:9
>     at async Promise.all (index 0)
> 23:01:14.309 DEBUG (m/reac/winds) On window.close: close to tray enabled

Running on Guix Linux.

**Comment by leafo** [comment]
Closing old issue, leave a comment if you're still having an issue. Not aware of any outstanding issues for this.
