### ISSUE TITLE
Feedback v26.1.9

### ISSUE THREAD

**Issue by dkNykita** [itchio/itch#3213]
Download stopped working, reinstall + manual clear didnt help. Keep getting error even with empty download queue.
Itch @ 26.1.9
Butler @ 15.24.0
Itch-setup @ 1.27.0
Windows 64-bit (win11)
sandbox enabled

`{"time":1734534273816,"level":20,"msg":"Calling Fetch.Commons","name":"mcall"}
{"time":1734534277826,"level":20,"msg":"Calling Profile.Data.Put","name":"mcall"}
{"time":1734534279112,"level":20,"msg":"Calling Fetch.Commons","name":"mcall"}
{"time":1734534280074,"level":20,"msg":"Download driver polling...","name":"m/reac/down/driver"}
{"time":1734534280074,"level":20,"msg":"Paused... current phase: RUNNING","name":"m/reac/down/driver"}
{"time":1734534280074,"level":20,"msg":"RUNNING => CANCELLING","name":"m/reac/down/driver-persistent-state"}
{"time":1734534280074,"level":20,"msg":"Cancelling downloads convo","name":"m/reac/down/driver-persistent-state"}
{"time":1734534280074,"level":20,"msg":"CANCELLING => IDLE","name":"m/reac/down/driver-persistent-state"}
{"time":1734534280074,"level":30,"msg":"Downloads stopped","name":"m/reac/down/driver-persistent-state"}
{"time":1734534280074,"level":50,"msg":"Caught butler error:","name":"mcall"}
{"time":1734534280074,"level":50,"msg":"butler version: undefined","name":"mcall"}
{"time":1734534280074,"level":50,"msg":"Golang stack:\nError\n    at RequestError.fromInternalCode (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1494:24)\n    at Conversation.cancel (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1206:47)\n    at State.cancel (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:21142:23)\n    at driverPoll (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:21221:29)\n    at C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:21193:15\n    at Timeout._onTimeout (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:14142:27)\n    at listOnTimeout (node:internal/timers:559:17)\n    at process.processTimers (node:internal/timers:502:7)","name":"mcall"}
{"time":1734534280074,"level":50,"msg":"JavaScript stack: Error: JSON-RPC error -1000: JSON-RPC conversation cancelled\n    at RequestError.fromInternalCode (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1490:16)\n    at Conversation.cancel (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1206:47)\n    at State.cancel (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:21142:23)\n    at driverPoll (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:21221:29)\n    at C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:21193:15\n    at Timeout._onTimeout (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:14142:27)\n    at listOnTimeout (node:internal/timers:559:17)\n    at process.processTimers (node:internal/timers:502:7)","name":"mcall"}
{"time":1734534280074,"level":50,"msg":"Error: JSON-RPC error -1000: JSON-RPC conversation cancelled\n    at RequestError.fromInternalCode (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1490:16)\n    at Conversation.cancel (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1206:47)\n    at State.cancel (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:21142:23)\n    at driverPoll (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:21221:29)\n    at C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:21193:15\n    at Timeout._onTimeout (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:14142:27)\n    at listOnTimeout (node:internal/timers:559:17)\n    at process.processTimers (node:internal/timers:502:7)","name":"m/reac/down/driver"}
{"time":1734534280074,"level":20,"msg":"A Downloads.Drive call finished, but another is already up.","name":"m/reac/down/driver"}
{"time":1734534281317,"level":20,"msg":"Calling Fetch.Commons","name":"mcall"}
{"time":1734534283922,"level":20,"msg":"Calling Profile.Data.Put","name":"mcall"}
{"time":1734534285796,"level":20,"msg":"Calling Fetch.Commons","name":"mcall"}
{"time":1734534286499,"level":20,"msg":"Download driver polling...","name":"m/reac/down/driver"}
{"time":1734534286499,"level":20,"msg":"Not paused... current phase: IDLE","name":"m/reac/down/driver"}
{"time":1734534286499,"level":20,"msg":"IDLE => STARTING","name":"m/reac/down/driver-persistent-state"}
{"time":1734534286499,"level":20,"msg":"Calling Downloads.Drive","name":"mcall"}
{"time":1734534286499,"level":20,"msg":"STARTING => RUNNING","name":"m/reac/down/driver-persistent-state"}
{"time":1734534286499,"level":30,"msg":"Downloads started","name":"m/reac/down/driver-persistent-state"}
{"time":1734534286501,"level":30,"msg":"Now driving downloads...","name":"m/reac/down/driver"}
{"time":1734534286828,"level":20,"msg":"Calling Fetch.Commons","name":"mcall"}
{"time":1734534288923,"level":20,"msg":"Calling Profile.Data.Put","name":"mcall"}
{"time":1734534290925,"level":20,"msg":"Calling Profile.Data.Put","name":"mcall"}
`

**Comment by dkNykita** [comment]
when attempting to update:

`{"time":1734535277399,"level":50,"msg":"Caught butler error:","name":"mcall"}
{"time":1734535277400,"level":50,"msg":"butler version: v15.24.0, built on Dec 13 2024 @ 02:12:46, ref f1203f79c4b65ef2201e95ca81b6b02b7d37cb04","name":"mcall"}
{"time":1734535277400,"level":50,"msg":"Golang stack:\nAlready have downloads in progress for World Tamer - https://deniam.itch.io/worldtamer, refusing to queue another one\ngithub.com/itchio/butler/endpoints/downloads.DownloadsQueue\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/endpoints/downloads/downloads_queue.go:53\ngithub.com/itchio/butler/endpoints/install.InstallQueue\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/endpoints/install/install_queue.go:272\ngithub.com/itchio/butler/endpoints/install.Register.(*InstallQueueType).Register.func3\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/messages/messages.go:1661\ngithub.com/itchio/butler/butlerd.(*Router).HandleRequest.func2\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/router.go:306\ngithub.com/itchio/butler/butlerd.(*Router).HandleRequest\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/router.go:315\ngithub.com/itchio/butler/butlerd.(*gatedHandler).HandleRequest\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/butlerd.go:159\ngithub.com/itchio/butler/butlerd/jsonrpc2.(*connImpl).handleIncomingMessage.func1\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/jsonrpc2/jsonrpc2.go:250\nruntime.goexit\n\tC:/Go/src/runtime/asm_amd64.s:1700\ngithub.com/itchio/butler/endpoints/install.InstallQueue\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/endpoints/install/install_queue.go:276\ngithub.com/itchio/butler/endpoints/install.Register.(*InstallQueueType).Register.func3\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/messages/messages.go:1661\ngithub.com/itchio/butler/butlerd.(*Router).HandleRequest.func2\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/router.go:306\ngithub.com/itchio/butler/butlerd.(*Router).HandleRequest\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/router.go:315\ngithub.com/itchio/butler/butlerd.(*gatedHandler).HandleRequest\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/butlerd.go:159\ngithub.com/itchio/butler/butlerd/jsonrpc2.(*connImpl).handleIncomingMessage.func1\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/jsonrpc2/jsonrpc2.go:250\nruntime.goexit\n\tC:/Go/src/runtime/asm_amd64.s:1700","name":"mcall"}
{"time":1734535277400,"level":50,"msg":"JavaScript stack: Error: Already have downloads in progress for World Tamer - https://deniam.itch.io/worldtamer, refusing to queue another one\n    at Conversation.handleMessage (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1140:28)\n    at Transform.<anonymous> (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1036:22)\n    at Transform.emit (node:events:513:28)\n    at addChunk (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33156:12)\n    at readableAddChunk (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33138:11)\n    at Readable.push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33099:10)\n    at Transform.push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:34128:32)\n    at push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:32475:10)\n    at Transform.transform [as _transform] (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:32446:7)\n    at Transform._read (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:34166:10)","name":"mcall"}
{"time":1734535277400,"level":50,"msg":"while reacting to queueGameUpdate: Error: Already have downloads in progress for World Tamer - https://deniam.itch.io/worldtamer, refusing to queue another one\n    at Conversation.handleMessage (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1140:28)\n    at Transform.<anonymous> (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1036:22)\n    at Transform.emit (node:events:513:28)\n    at addChunk (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33156:12)\n    at readableAddChunk (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33138:11)\n    at Readable.push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33099:10)\n    at Transform.push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:34128:32)\n    at push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:32475:10)\n    at Transform.transform [as _transform] (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:32446:7)\n    at Transform._read (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:34166:10)"}
{"time":1734535277400,"level":50,"msg":"Caught butler error:","name":"mcall"}
{"time":1734535277400,"level":50,"msg":"butler version: v15.24.0, built on Dec 13 2024 @ 02:12:46, ref f1203f79c4b65ef2201e95ca81b6b02b7d37cb04","name":"mcall"}
{"time":1734535277400,"level":50,"msg":"Golang stack:\nAlready have downloads in progress for Dimension 69 - https://dussop.itch.io/dimension-69, refusing to queue another one\ngithub.com/itchio/butler/endpoints/downloads.DownloadsQueue\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/endpoints/downloads/downloads_queue.go:53\ngithub.com/itchio/butler/endpoints/install.InstallQueue\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/endpoints/install/install_queue.go:272\ngithub.com/itchio/butler/endpoints/install.Register.(*InstallQueueType).Register.func3\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/messages/messages.go:1661\ngithub.com/itchio/butler/butlerd.(*Router).HandleRequest.func2\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/router.go:306\ngithub.com/itchio/butler/butlerd.(*Router).HandleRequest\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/router.go:315\ngithub.com/itchio/butler/butlerd.(*gatedHandler).HandleRequest\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/butlerd.go:159\ngithub.com/itchio/butler/butlerd/jsonrpc2.(*connImpl).handleIncomingMessage.func1\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/jsonrpc2/jsonrpc2.go:250\nruntime.goexit\n\tC:/Go/src/runtime/asm_amd64.s:1700\ngithub.com/itchio/butler/endpoints/install.InstallQueue\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/endpoints/install/install_queue.go:276\ngithub.com/itchio/butler/endpoints/install.Register.(*InstallQueueType).Register.func3\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/messages/messages.go:1661\ngithub.com/itchio/butler/butlerd.(*Router).HandleRequest.func2\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/router.go:306\ngithub.com/itchio/butler/butlerd.(*Router).HandleRequest\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/router.go:315\ngithub.com/itchio/butler/butlerd.(*gatedHandler).HandleRequest\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/butlerd.go:159\ngithub.com/itchio/butler/butlerd/jsonrpc2.(*connImpl).handleIncomingMessage.func1\n\tC:/msys64/home/amos/gitlab/builds/GicXyNJy/1/itchio/butler/butlerd/jsonrpc2/jsonrpc2.go:250\nruntime.goexit\n\tC:/Go/src/runtime/asm_amd64.s:1700","name":"mcall"}
{"time":1734535277400,"level":50,"msg":"JavaScript stack: Error: Already have downloads in progress for Dimension 69 - https://dussop.itch.io/dimension-69, refusing to queue another one\n    at Conversation.handleMessage (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1140:28)\n    at Transform.<anonymous> (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1036:22)\n    at Transform.emit (node:events:513:28)\n    at addChunk (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33156:12)\n    at readableAddChunk (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33138:11)\n    at Readable.push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33099:10)\n    at Transform.push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:34128:32)\n    at push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:32475:10)\n    at Transform.transform [as _transform] (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:32446:7)\n    at Transform._read (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:34166:10)","name":"mcall"}
{"time":1734535277400,"level":50,"msg":"while reacting to queueGameUpdate: Error: Already have downloads in progress for Dimension 69 - https://dussop.itch.io/dimension-69, refusing to queue another one\n    at Conversation.handleMessage (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1140:28)\n    at Transform.<anonymous> (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:1036:22)\n    at Transform.emit (node:events:513:28)\n    at addChunk (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33156:12)\n    at readableAddChunk (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33138:11)\n    at Readable.push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:33099:10)\n    at Transform.push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:34128:32)\n    at push (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:32475:10)\n    at Transform.transform [as _transform] (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:32446:7)\n    at Transform._read (C:\\Users\\domca\\AppData\\Local\\itch\\app-26.1.9\\resources\\app\\dist\\main\\main.bundle.js:34166:10)"}
{"time":1734535287438,"level":20,"msg":"Calling Profile.Data.Put","name":"mcall"}
`
