### ISSUE TITLE
[linux / ubuntu1510_64] Issue for v0.12.6: socket hang up

### ISSUE THREAD

**Issue by puldzian** [itchio/itch#378]
This 
tried to login for the first time and then > 

Problem w trakcie instalacji [installation error]: Error: socket hang up
    at createHangUpError (_http_client.js:209:15)
    at TLSSocket.socketCloseListener (_http_client.js:241:23)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)

Ubuntu 15.10 64bit

**Comment by fasterthanlime** [comment]
@puldzian this issue has been popping up here and there and is hard to reproduce — trying again should probably work.

**Comment by puldzian** [comment]
Yes, I've managed to login after a few tries, thanks.
