### ISSUE TITLE
Java Game Crash on Close

### ISSUE THREAD

**Issue by JoseRivas1998** [itchio/itch#546]
I built a game in Java with libGDX that is run in a .jar file. I was testing it out, and when I closed the game, I got a message saying it crashed.

I will past the console readout bellow.

```
[2016-04-06 @ 21:43:53] ←[35m[sagas/tasks] Task ended, err: Crash: application crashed
    at E:\Documents\GitHub\itch\appsrc\tasks\launch\native.js:38:11
From previous event:
    at sh (E:\Documents\GitHub\itch\appsrc\tasks\launch\native.js:19:16)
    at launchExecutable (E:\Documents\GitHub\itch\appsrc\tasks\launch\native.js:138:12)
    at E:\Documents\GitHub\itch\appsrc\tasks\launch\native.js:186:10
    at undefined.next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at launch (E:\Documents\GitHub\itch\appsrc\tasks\launch\native.js:142:31)
    at E:\Documents\GitHub\itch\appsrc\tasks\launch.js:50:9
    at undefined.next (native)
From previous event:
    at start (E:\Documents\GitHub\itch\appsrc\tasks\launch.js:23:31)
    at runCallEffect (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:296:19)
    at runEffect (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:242:399)
    at E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:502:14
    at Array.forEach (native)
    at runRaceEffect (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:501:10)
    at runEffect (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:242:304)
    at next (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:141:9)
    at currCb (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:194:7)
    at runSelectEffect (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:512:7)
    at runEffect (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:242:848)
    at next (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:141:9)
    at currCb (E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:194:7)
    at E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\proc.js:283:14
    at E:\Documents\GitHub\itch\node_modules\redux-saga\lib\internal\utils.js:93:12
    at run (E:\Documents\GitHub\itch\node_modules\core-js\modules\es6.promise.js:89:22)
    at E:\Documents\GitHub\itch\node_modules\core-js\modules\es6.promise.js:102:28
    at flush (E:\Documents\GitHub\itch\node_modules\core-js\modules\_microtask.js:14:5)
    at doNTCallback0 (node.js:443:9)←[39m
```

**Comment by fasterthanlime** [comment]
Well the app is doing it's job (although a bit verbose...). Looks like the java process returned a non-zero exit code, that's all!
