### ISSUE TITLE
Login hangs on "Making sure we have everything set up..." when 7za isn't available

### ISSUE THREAD

**Issue by jhasse** [itchio/itch#557]
Trying to login the app hangs showing "Making sure we have everything set up...". The stop watch is still being animated, this is the console output:

```
$ npm start

> itch@0.14.29-canary start /home/jhasse/git/itch
> grunt && electron . --color

.........................
[2016-04-11 @ 19:07:33] [itch] using electron 0.37.2
[2016-04-11 @ 19:07:33] [market] loading market db from /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:33] [market] cleaning temporary files from /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:33] [market] loading records for /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:33] [market] migrating old entries for /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:33] [market] populating in-memory DB with disk records
[2016-04-11 @ 19:07:33] [market] done loading db from /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:33] [market] closing db /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:33] [self-update] Installed!
[2016-04-11 @ 19:07:33] [self-update] Update feed: http://nuts-canary.itch.ovh/update/linux_x64/0.14.29-canary
[2016-04-11 @ 19:07:33] [market] loading market db from /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:33] [market] cleaning temporary files from /home/jhasse/.config/itch/marketdb
redux-saga error: : uncaught
Error: 7-zip missing: 7za must be in $PATH
(Try installing p7zip-full)
    at Object.self.7za.onMissing.platform [as onMissing] (/home/jhasse/git/itch/appsrc/util/ibrew/formulas.js:14:13)
    at self.fetch (/home/jhasse/git/itch/appsrc/util/ibrew.js:67:17)
    at undefined.next (native)
    at next (/home/jhasse/git/itch/node_modules/redux-saga/lib/internal/proc.js:139:61)
    at currCb (/home/jhasse/git/itch/node_modules/redux-saga/lib/internal/proc.js:194:7)
    at /home/jhasse/git/itch/node_modules/redux-saga/lib/internal/proc.js:252:14
    at run (/home/jhasse/git/itch/node_modules/core-js/modules/es6.promise.js:89:22)
    at /home/jhasse/git/itch/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/home/jhasse/git/itch/node_modules/core-js/modules/_microtask.js:14:5)
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
redux-saga error: fetch: uncaught
undefined
redux-saga error: setup: uncaught
undefined
[2016-04-11 @ 19:07:33] [market] loading records for /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:33] [market] migrating old entries for /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:33] [market] populating in-memory DB with disk records
[2016-04-11 @ 19:07:33] [market] done loading db from /home/jhasse/.config/itch/marketdb
[2016-04-11 @ 19:07:34] [locales] Not downloading locales in development, export DID_I_STUTTER=1 to override
[2016-04-11 @ 19:07:35] [fetch-saga] Not logged in, not fetching anything yet
[2016-04-11 @ 19:07:35] [self-update] Checking...
[2016-04-11 @ 19:07:36] [self-update] HTTP GET http://nuts-canary.itch.ovh/update/linux_x64/0.14.29-canary: 204
[2016-04-11 @ 19:08:26] [market] loading market db from /home/jhasse/.config/itch/users/59535/marketdb
[2016-04-11 @ 19:08:26] [market] cleaning temporary files from /home/jhasse/.config/itch/users/59535/marketdb
[2016-04-11 @ 19:08:26] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:08:26] [market] loading records for /home/jhasse/.config/itch/users/59535/marketdb
[2016-04-11 @ 19:08:26] [market] migrating old entries for /home/jhasse/.config/itch/users/59535/marketdb
[2016-04-11 @ 19:08:26] [market] populating in-memory DB with disk records
[2016-04-11 @ 19:08:26] [market] done loading db from /home/jhasse/.config/itch/users/59535/marketdb
[2016-04-11 @ 19:08:26] [updater] Regularly scheduled check for game updates...
[2016-04-11 @ 19:08:46] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:09:09] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:09:17] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:09:37] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:10:39] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:10:46] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:10:51] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:10:53] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:10:57] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:11:22] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:11:37] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:11:47] [fetch-saga] Fetching the usuals
[2016-04-11 @ 19:11:52] [fetch-saga] Fetching the usuals
```

(I've exited the app manually)

Installing 7zip fixed it, but it should probably show a better error message in GUI and not hang there ;)

**Comment by ogbaba** [comment]
I also experience this issue
EDIT: It seems even though p7zip is installed, it won't update :cry:

**Comment by fasterthanlime** [comment]
> EDIT: It seems even though p7zip is installed, it won't update

Hm? Are you talking about self-update? Or updating 7-zip? The app doesn't update external 7-zips.

As for self-update: on Linux, app updates are distributed through the package repository for your appropriate distribution: https://docs.itch.ovh/itch/master/installing/linux/

**Comment by ogbaba** [comment]
@fasterthanlime in fact i misread the issue, I have a no 7za stuff message in the terminal but also an in app message saying it is downloading an update but it stays forever :octopus: 

<a href="http://i.imgur.com/FnCIMvH.png">
  <img src="http://imgur.com/FnCIMvHl.png" />
</a>

**EDIT : Well I think it has nothing to see, I think I will make a new issue for that downloading message stuff**

**Comment by fasterthanlime** [comment]
Here's what the app shows now:

![2016-05-06-220049_1080x710_scrot](https://cloud.githubusercontent.com/assets/7998310/15084778/090874ee-13d6-11e6-8dc0-a612d94dd4f7.png)

That gives you time to install p7zip-full and click the arrow button (retry), and then the setup will succeed.
