### ISSUE TITLE
Blank collections

### ISSUE THREAD

**Issue by erbridge** [itchio/itch#657]
In the collections section, there are 3 blank collections (to match the 3 real collections). Clicking them shows "Loading... A collection of {{itemCount}} items", and nothing loads.

**Comment by valrus** [comment]
Same here. OS X 10.11.5, itch v18.0.0.

**Comment by fasterthanlime** [comment]
@valrus when this happens (provided it still happens), can you hit Shift+F12 and report if there's any errors in the console?

**Comment by valrus** [comment]
There were not, but the latest update (v18.2.0) seems to have fixed it!

Amos Wenger wrote:

**Comment by erbridge** [comment]
Not fixed for me on Arch Linux, itch v18.2.0. Nothing in the console, but I just quit with the Collections view focused, and when I reopened it, the app presented a popup claiming that it had crashed (though it didn't actually die). This is the crash log:

```
API Error: collection_id must be an integer
    at /usr/lib/itch/resources/app.asar/appsrc/util/api.js:79:13
    at undefined.next (native)
    at done (/usr/lib/itch/resources/app.asar/node_modules/needle/lib/needle.js:377:14)
    at PassThrough.<anonymous> (/usr/lib/itch/resources/app.asar/node_modules/needle/lib/needle.js:576:9)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Client.request (/usr/lib/itch/resources/app.asar/appsrc/util/api.js:52:62)
    at /usr/lib/itch/resources/app.asar/appsrc/util/api.js:137:30
    at undefined.next (native)
From previous event:
    at AuthenticatedClient.request (/usr/lib/itch/resources/app.asar/appsrc/util/api.js:135:62)
    at /usr/lib/itch/resources/app.asar/appsrc/util/api.js:166:23
    at undefined.next (native)
From previous event:
    at AuthenticatedClient.collection (/usr/lib/itch/resources/app.asar/appsrc/util/api.js:165:35)
    at Object.<anonymous> (/usr/lib/itch/resources/app.asar/appsrc/util/fetch.js:238:40)
    at undefined.next (native)
From previous event:
    at Object.collectionLazily (/usr/lib/itch/resources/app.asar/app/util/fetch.js:257:18)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/navigation.js:55:36
    at undefined.next (native)
From previous event:
    at retrieveTabData (/usr/lib/itch/resources/app.asar/app/reactors/navigation.js:114:17)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/navigation.js:147:24
    at undefined.next (native)
From previous event:
    at doFetchTabData (/usr/lib/itch/resources/app.asar/app/reactors/navigation.js:138:18)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/navigation.js:226:7
    at undefined.next (native)
From previous event:
    at sessionReady (/usr/lib/itch/resources/app.asar/app/reactors/navigation.js:245:18)
From previous event:
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/combine.js:20:15
    at undefined.next (native)
From previous event:
    at _underline.each.call (/usr/lib/itch/resources/app.asar/appsrc/reactors/combine.js:18:5)
    at _.each._.forEach (/usr/lib/itch/resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:153:9)
    at Array.<anonymous> (/usr/lib/itch/resources/app.asar/node_modules/underline/underline.js:23:14)
    at executeBound (/usr/lib/itch/resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:701:67)
    at Array.bound (/usr/lib/itch/resources/app.asar/node_modules/underline/node_modules/underscore/underscore.js:733:14)
    at /usr/lib/itch/resources/app.asar/appsrc/reactors/combine.js:18:5
    at route (/usr/lib/itch/resources/app.asar/appsrc/reactors/route.js:5:5)
    at postDispatchCallback (/usr/lib/itch/resources/app.asar/appsrc/store/browser-store.js:46:7)
    at doDispatch (/usr/lib/itch/resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:74:9)
    at Object.store.dispatch (/usr/lib/itch/resources/app.asar/node_modules/redux-electron-store/lib/electronBrowserEnhancer.js:128:9)
    at Immediate.setImmediate (/usr/lib/itch/resources/app.asar/appsrc/reactors/session.js:31:15)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by fasterthanlime** [comment]
@erbridge if you still have the 'blank collection' tab around, do you mind sending me the contents of your `~/.config/itch/marketdb/itchAppTabs/x` ?

**Comment by erbridge** [comment]
`~/.config/itch/marketdb/` only has a `caves` subdirectory.

**Comment by fasterthanlime** [comment]
woops, I meant `~/.config/itch/users/XXX/marketdb/...`

**Comment by erbridge** [comment]
Aha. Contents is:

``` json
{"current":"collections","items":[]}
```

**Comment by erbridge** [comment]
That's looking at the Collections tab. Looking at one of the broken collections themselves:

``` json
{"current":"5a11af21-cf27-4392-b6c2-e6ada7f605ce","items":[{"id":"5a11af21-cf27-4392-b6c2-e6ada7f605ce","path":"collections/undefined"}]}
```

**Comment by fasterthanlime** [comment]
well, that's about what I expected. how does the 'collections' view look? does it display the right thumbnails? are there any differences with what the website shows (at https://itch.io/my-collections)? the question is why clicking on an item of 'collections' lead to a tab with path `collection/undefined`.

**Comment by erbridge** [comment]
Collections view:

![image](https://cloud.githubusercontent.com/assets/1027364/16568493/c7be1220-4222-11e6-9f98-b202c53e0793.png)

One of the blank collections:

![image](https://cloud.githubusercontent.com/assets/1027364/16568500/e299916e-4222-11e6-92a8-43703c890570.png)

**Comment by fasterthanlime** [comment]
@erbridge current working theory: a previous version of the app corrupted your marketdb. Can you try 1) quitting the app completely 2) wiping `~/.config/itch/users/XXX/marketdb/collections` completely 3) restarting the app?

**Comment by erbridge** [comment]
Ok, problem solved. There were six directories in there, three called sensible ids, and the other three called `1`, `2`, `3` (may have been `0` based...). Clearing them all fixed the issue. Looks like it might have been a case of iterating through them and using the iteration index instead of the id at one point.

**Comment by fasterthanlime** [comment]
> Looks like it might have been a case of iterating through them and using the iteration index instead of the id at one point.

Looks like it! Thanks for seeing this investigation through - closing!
