### ISSUE TITLE
itch sandbox and Windows user account's security policies

### ISSUE THREAD

**Issue by quyse** [itchio/itch#776]
I've tried to setup itch sandbox on Windows Server 2016 Technical Preview 5, but it was unsuccessful. I've checked "Enable itch.io sandbox", then tried to run a game, got a popup asking if I'm OK with performing first-time sandbox setup, agreed, entered administrator password, and then got an itch launch error message: `error(s) while installing sandbox: Error: adminRunScript failed with code 1`.

I've tried to run `net user itch-player salt /add` manually, and got a message that the password doesn't meet password policy requirements. Apparently the system had enabled the policy for strong passwords, which can be found in `Local Security Policy` applet as `Security Settings` -> `Account Policies` -> `Password Policy` -> `Password must meet complexity requirements`. Exact requirements from the setting's description:

```
Not contain the user's account name or parts of the user's full name that exceed two consecutive characters
Be at least six characters in length
Contain characters from three of the following four categories:
English uppercase characters (A through Z)
English lowercase characters (a through z)
Base 10 digits (0 through 9)
Non-alphabetic characters (for example, !, $, #, %)
Complexity requirements are enforced when passwords are changed or created.
```

Clearly the password `salt` violates this policy. After disabling the policy itch app was able to perform setup and run a game under sandbox. Note that this particular policy was enabled by default on my system (presumably because it's server edition).

I guess the simplest fix would be to hardcode some acceptable password like `PleaseN0tAgainWindows!` instead of `salt`. However there're some other policies related to password, like password length/age limits - they were disabled by default, but someone may have them enabled. Probably itch has to regenerate password from time to time?

**Comment by fasterthanlime** [comment]
> I guess the simplest fix would be to hardcode some acceptable password like PleaseN0tAgainWindows! instead of salt.

I think we'll have to live with a fix like that for now. The problem with password rotation is that it'll require elevated privileges every time the app wants to change it :( And I'm not making a backdoor where the app has elevated privileges whenever it wants (ie. what Steam does).

I think supporting the default complexity requirements policy is already quite an improvement on `salt`!

**Comment by quyse** [comment]
> The problem with password rotation is that it'll require elevated privileges every time the app wants to change it :(

I just found out that it isn't the case: `NetUserChangePassword` ([MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa370650)) function allows to change password for a user if you know old password, without having administrative privileges (essentially implementing a way for a user to change their own password). I just verified it on the same Windows system as above: I called the function under normal non-administrator user account (not `itch-player`), specified `itch-player` user name, old password and some new password, and checked that `itch-player`'s password has been successfully changed.

So maybe it's worth to make use of this function, trying to change `itch-player`'s password to newly generated one every time we suspect that password has expired (e.g. logon fails).

**Comment by fasterthanlime** [comment]
That sounds really promising! 18.3.0 is running late so it'll have to be for another point release, but since there's a right way to do it, I don't see why we couldn't :)

Since it's a win32 API call, we'll probably need a new subcommand in [elevate](https://github.com/itchio/elevate).

**Comment by quyse** [comment]
Today I'm getting the following error in logs when I try to run any game under sandbox:

```
[2016-09-15 @ 12:05:54.869] [tasks/launch/native] out: API = LogonUser.
[2016-09-15 @ 12:05:54.869] [tasks/launch/native] out: error code = 1330.
[2016-09-15 @ 12:05:54.869] [tasks/launch/native] out: message    = The password for this account has expired.
[2016-09-15 @ 12:05:54.869] [tasks/launch/native] out: .
[2016-09-15 @ 12:05:54.870] [tasks/launch/native] err: LogonUser
```

This is on Windows 10 Home. I did not change any account policies (in fact, `gpedit.msc` and `secpol.msc` are apparently absent on Home edition), and anyway the password somehow got expired. That prevents me from running any game under sandbox.

I'm not sure why it's happening, my own user account on this system haven't got expired despite last time I changed my password was long time ago.

I've seen that error already on Server edition, but I knew that 42-day password policy was enabled there. Here at Home edition I don't even know how to enable/disable those policies.

**Comment by fasterthanlime** [comment]
@quyse I started seeing the exact same behavior a few days ago!

.@granpc & I are working on a fix (ie. rotating the password as needed).

**Comment by fasterthanlime** [comment]
Fixed by https://github.com/itchio/itch/commit/80b321113a6b15440a6fcdffa34630cfe02fac50 (app now refreshes password when it expires, stored in the registry, itch-player users are by-account now).

**Comment by quyse** [comment]
@fasterthanlime I've updated to the new version of itch on Windows Server 2016, and tried to run a game. itch asked for permission to perform one-time sandbox setup, despite that it's already done and itch-player user already exists (but not working due to expired password). Ok, I agreed, but setup fails with error `error(s) while installing sandbox: Error: setup failed with code 1. out = , err = [elevate] isolate.exe --setup [elevate] runas isolate.exe --setup` and log:

```
[2016-09-20 @ 15:17:58.496] [tasks/launch] crashed with error(s) while installing sandbox: Error: setup failed with code 1. out = , err = [elevate] isolate.exe --setup 
[elevate] runas isolate.exe --setup 

[2016-09-20 @ 15:17:58.496] [tasks/launch] Error: error(s) while installing sandbox: Error: setup failed with code 1. out = , err = [elevate] isolate.exe --setup 
[elevate] runas isolate.exe --setup 

    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\tasks\launch\native.js:154:13
From previous event:
    at launch (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\app\tasks\launch\native.js:366:17)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\tasks\launch.js:293:11
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at doStart (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\app\tasks\launch.js:235:18)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\tasks\launch.js:74:18
    at next (<anonymous>)
From previous event:
    at start (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\app\tasks\launch.js:437:17)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\reactors\tasks\start-task.js:53:20
    at next (<anonymous>)
From previous event:
    at startTask (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\app\reactors\tasks\start-task.js:67:17)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\reactors\tasks\queue-game.js:100:23
    at next (<anonymous>)
From previous event:
    at startCave (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\app\reactors\tasks\queue-game.js:123:18)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\reactors\tasks\queue-game.js:25:11
    at next (<anonymous>)
From previous event:
    at queueGame (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\app\reactors\tasks\queue-game.js:94:17)
From previous event:
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\reactors\combine.js:20:15
    at next (<anonymous>)
From previous event:
    at _underline.each.call (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\reactors\combine.js:18:5)
    at _.each._.forEach (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:153:9)
    at Array.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\node_modules\underline\underline.js:23:14)
    at executeBound (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:701:67)
    at Array.bound (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:733:14)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\reactors\combine.js:18:5
    at route (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\reactors\route.js:5:5)
    at postDispatchCallback (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\appsrc\store\browser-store.js:46:7)
    at doDispatch (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:146:11)
    at EventEmitter.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:129:15)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.10.0\resources\electron.asar\browser\api\web-contents.js:210:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
[2016-09-20 @ 15:17:58.497] [diego] diego here, looking around
Caption                                                     OSArchitecture  Version     
Microsoft Windows Server 2016 Standard Technical Preview 5  64-bit          10.0.14300  
```

I tried to remove itch-player user and it's home folder, but sandbox setup still fails. Disabling account policies don't help either.

**Comment by fasterthanlime** [comment]
@quyse the new code actually creates a differently-named user (something like `itch-player-ab9876c`). Did you see an UAC prompt after clicking 'Proceed' on the itch app dialog?

**Comment by fasterthanlime** [comment]
@quyse also, does it work fine on your Windows 10 install? In WS2016, do you see anything in the registry under `HKEY_CURRENT_USER\Software\itch` ?

**Comment by quyse** [comment]
@fasterthanlime Yes, there is an UAC prompt for isolate.exe to be run under Administrator account.
From what I can see no new users are created with whatever names.
I see `HKEY_CURRENT_USER\Software\itch\Sandbox` folder in registry, but both itch and Sandbox folders are empty.
I haven't checked Windows 10 yet, because I need to reboot my PC for that :) And I can access WS2016 because it's VM hosted in my Linux system. I'll check W10 later.

**Comment by fasterthanlime** [comment]
Just tested on a Windows Server 2012 VM, and it worked beautifully:

<img width="1014" alt="screen shot 2016-09-20 at 14 42 46" src="https://cloud.githubusercontent.com/assets/7998310/18670500/8bf428aa-7f40-11e6-9aa4-cfc09f935bc4.png">

Note that the user doesn't appear in the regular Users list. You can open that particular user manager by doing `Win+R` (execute) and typing `lusrmgr.msc`.

My current theory is that WS2016 doesn't like some of the APIs [isolate](https://github.com/itchio/isolate) is using! (maybe it doesn't like it writing to the registry or something). Maybe you can dig in the some of the Windows logging tools to see if a particular call failed?

To test outside the app, you can call:

``` batch
elevate.exe isolate.exe --setup
```

(and then `echo %ERRORLEVEL%` to make sure it's `0`). This should pop an UAC prompt and attempt to set up the user.

**Comment by quyse** [comment]
@fasterthanlime I think I figured out the problem. On my system current user (`gitlab-runner`) doesn't have administrator rights, i.e. cannot be elevated. Therefore UAC asks for running under `Administrator` account, which means `isolate` writes into wrong part of Registry. I guess you test under user which has administrator rights?

**Comment by fasterthanlime** [comment]
@quyse correct! We assume whoever is using the sandbox has administrator rights. So, isolate could be fixed if we passed explicitly which user the sandbox is for afaict? @GranPC

**Comment by quyse** [comment]
@fasterthanlime Yeah, you can write under `HKEY_USERS\<user-id>\Software\itch`. Or maybe perform reads and writes to registry only while being non-elevated. I wonder if there's a better way like performing admin logon without loading Administrator profile, so `HKEY_CURRENT_USER` would still be user's. On Linux it's possible with `sudo` I think :)

**Comment by fasterthanlime** [comment]
> On Linux it's possible

don't tease me 🐼

**Comment by quyse** [comment]
@fasterthanlime BTW creating sandbox was failing because it was actually created at first time and registry values were written, so then `isolate` wasn't even trying to create anything. I deleted that user account manually because itch wasn't working, but registry values were still in place. Maybe it must check that username and password from registry are actually valid! After removing values from admin's registry it created sandbox successfully, and then after manual moving values from admin's registry into user's registry itch finally allowed me to run game under sandbox.

**Comment by GranPC** [comment]
> So, isolate could be fixed if we passed explicitly which user the sandbox is for afaict?

Yup, that should do the trick. I'll start testing against this scenario and roll out a fix soon. Thanks for testing @quyse!
