### ISSUE TITLE
Unable to install tool: `lsar failed with code 1`

### ISSUE THREAD

**Issue by quyse** [itchio/itch#857]
Not sure what has changed, but I'm not able to install https://quyse.itch.io/flaw on Windows (in QEMU). With clean itch profile, first time install fails without any notice (`Install` button just turns to `Installing...` and then back to `Install`). Manual downloading-extracting-running `flaw-model-editor-windows.zip` from the website works, it doesn't seem that something's wrong with the zip. Here is part of the `itch.txt` log:

```
[2016-08-26 @ 07:25:26.983] [reactors/tasks] No cave for 68784, attempting install
[2016-08-26 @ 07:25:26.986] [reactors/tasks] About to start find-upload (e671ec98-6b68-464b-ac43-6362ee2730de)
[2016-08-26 @ 07:25:26.987] [reactors/tasks] Starting find-upload (e671ec98-6b68-464b-ac43-6362ee2730de)...
[2016-08-26 @ 07:25:27.176] [tasks/find-upload] got a list of 3 uploads (without download key)
[2016-08-26 @ 07:25:27.177] [tasks/find-upload] final uploads: [
  {
    "filename": "flaw-model-editor-windows.zip",
    "updatedAt": "2016-08-26 06:29:14",
    "buildId": 5011,
    "id": 213893,
    "pOsx": false,
    "channelName": "model-editor-windows",
    "position": 2,
    "gameId": 68784,
    "preorder": false,
    "pWindows": true,
    "createdAt": "2016-05-24 17:58:30",
    "size": 2644288,
    "pLinux": false,
    "type": "default",
    "build": {
      "parentBuildId": 4901,
      "updatedAt": "2016-08-26 06:28:49",
      "version": 29,
      "id": 5011,
      "state": "completed",
      "user": {
        "url": "https://quyse.itch.io",
        "username": "quyse",
        "id": 40551,
        "coverUrl": "https://img.itch.io/aW1hZ2UyL3VzZXIvNDA1NTEvMTE5MDU0LmpwZw==/100x100%23/EVUySj.jpg"
      },
      "files": [
        {
          "updatedAt": "2016-08-26 06:29:04",
          "size": 3485,
          "id": 14904,
          "type": "signature",
          "subType": "default",
          "createdAt": "2016-08-26 06:28:51",
          "state": "uploaded"
        },
        {
          "updatedAt": "2016-08-26 06:29:04",
          "size": 2332927,
          "id": 14903,
          "type": "patch",
          "subType": "default",
          "createdAt": "2016-08-26 06:28:50",
          "state": "uploaded"
        },
        {
          "updatedAt": "2016-08-26 06:29:14",
          "size": 2644288,
          "id": 14907,
          "type": "archive",
          "subType": "default",
          "createdAt": "2016-08-26 06:29:06",
          "state": "uploaded"
        }
      ],
      "createdAt": "2016-08-26 06:28:49"
    },
    "pAndroid": false,
    "demo": false,
    "score": 600
  }
]
[2016-08-26 @ 07:25:27.177] [reactors/tasks] Checking results for find-upload (e671ec98-6b68-464b-ac43-6362ee2730de)...
[2016-08-26 @ 07:25:27.177] [reactors/tasks] Task results: {
  "uploads": [
    {
      "filename": "flaw-model-editor-windows.zip",
      "updatedAt": "2016-08-26 06:29:14",
      "buildId": 5011,
      "id": 213893,
      "pOsx": false,
      "channelName": "model-editor-windows",
      "position": 2,
      "gameId": 68784,
      "preorder": false,
      "pWindows": true,
      "createdAt": "2016-05-24 17:58:30",
      "size": 2644288,
      "pLinux": false,
      "type": "default",
      "build": {
        "parentBuildId": 4901,
        "updatedAt": "2016-08-26 06:28:49",
        "version": 29,
        "id": 5011,
        "state": "completed",
        "user": {
          "url": "https://quyse.itch.io",
          "username": "quyse",
          "id": 40551,
          "coverUrl": "https://img.itch.io/aW1hZ2UyL3VzZXIvNDA1NTEvMTE5MDU0LmpwZw==/100x100%23/EVUySj.jpg"
        },
        "files": [
          {
            "updatedAt": "2016-08-26 06:29:04",
            "size": 3485,
            "id": 14904,
            "type": "signature",
            "subType": "default",
            "createdAt": "2016-08-26 06:28:51",
            "state": "uploaded"
          },
          {
            "updatedAt": "2016-08-26 06:29:04",
            "size": 2332927,
            "id": 14903,
            "type": "patch",
            "subType": "default",
            "createdAt": "2016-08-26 06:28:50",
            "state": "uploaded"
          },
          {
            "updatedAt": "2016-08-26 06:29:14",
            "size": 2644288,
            "id": 14907,
            "type": "archive",
            "subType": "default",
            "createdAt": "2016-08-26 06:29:06",
            "state": "uploaded"
          }
        ],
        "createdAt": "2016-08-26 06:28:49"
      },
      "pAndroid": false,
      "demo": false,
      "score": 600
    }
  ]
}
[2016-08-26 @ 07:25:27.178] [reactors/tasks] Task ended, err: <none>
[2016-08-26 @ 07:25:27.183] [reactors/tasks] Should download 213893, has dl key ? false
[2016-08-26 @ 07:25:27.221] [download-watcher] 1cf052e2-aad9-4509-a98b-cde176278e49 is the new active download
[2016-08-26 @ 07:25:27.221] [download-watcher] Starting download...
[2016-08-26 @ 07:25:27.413] [tasks/download] downloading from commondatastorage.googleapis.com
[2016-08-26 @ 07:25:27.414] [tasks/download] downloading to C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip
[2016-08-26 @ 07:25:27.414] [tasks/download] starting download!
[2016-08-26 @ 07:25:27.415] [tasks/download] making dir
[2016-08-26 @ 07:25:27.415] [tasks/download] butler download
[2016-08-26 @ 07:25:28.877] [tasks/download] finished
[2016-08-26 @ 07:25:28.877] [download-watcher] Download ended, err: <none>
[2016-08-26 @ 07:25:28.879] [reactors/tasks] Download finished, installing..
[2016-08-26 @ 07:25:28.881] [reactors/tasks] About to start install (1324293a-3e79-40bd-b058-992263a40ac5)
[2016-08-26 @ 07:25:28.890] [reactors/tasks] Starting install (1324293a-3e79-40bd-b058-992263a40ac5)...
[2016-08-26 @ 07:25:28.894] [download-watcher] Download done!
[2016-08-26 @ 07:25:28.898] [tasks/install] buildId: undefined => 5011
[2016-08-26 @ 07:25:28.902] [tasks/install] comparing mtimes, installed = NaN, archive = Fri Aug 26 2016 07:25:28 GMT+0300 (Russia TZ 2 Standard Time)
[2016-08-26 @ 07:25:28.906] [install/core] retrieving installer type of C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip from cache
[2016-08-26 @ 07:25:28.906] [install/core] invalid installer name stored: undefined - discarding
[2016-08-26 @ 07:25:28.910] [install/core] sniffed type {"ext":"zip","mime":"application/zip"} for C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip
[2016-08-26 @ 07:25:28.978] [download-watcher] Cancelling/clearing out last download
[2016-08-26 @ 07:25:29.046] [installers/archive] extracting archive 'C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip' to 'C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip-stage'
[2016-08-26 @ 07:25:29.050] [spawn] spawning lsar with args -j C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip
[2016-08-26 @ 07:25:29.103] [util/extract] archive contains 1 files, 8.75 MB total
[2016-08-26 @ 07:25:29.104] [spawn] spawning unar with args -force-overwrite -no-directory -output-directory C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip-stage C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip
[2016-08-26 @ 07:25:29.224] [installers/archive] extracted all files C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip into staging area
[2016-08-26 @ 07:25:29.233] [installers/archive] found a 'exe': C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip-stage\model-editor.exe
[2016-08-26 @ 07:25:29.234] [installers/archive] installing it with sniff opts: {
  "archivePath": "C:\\Users\\gitlab-runner\\AppData\\Roaming\\itch\\downloads\\213893-5011.zip-stage\\model-editor.exe",
  "disableCache": true
}
[2016-08-26 @ 07:25:29.235] [install/core] sniffed type {"ext":"exe","mime":"application/x-msdownload"} for C:\Users\gitlab-runner\AppData\Roaming\itch\downloads\213893-5011.zip-stage\model-editor.exe
[2016-08-26 @ 07:25:29.240] [installers/exe] got cave: {
  "id": "dd442de8-e5c1-49e5-b740-45c723ff2cd6",
  "gameId": 68784,
  "game": {
    "pAndroid": false,
    "id": 68784,
    "classification": "tool",
    "publishedAt": "2016-05-24 17:26:22",
    "url": "https://quyse.itch.io/flaw",
    "canBeBought": false,
    "inPressSystem": false,
    "published": true,
    "viewsCount": 127,
    "createdAt": "2016-05-24 17:26:22",
    "pOsx": true,
    "pWindows": true,
    "shortText": "FLAW is an experimental Haskell game engine",
    "title": "FLAW",
    "pLinux": true,
    "type": "default",
    "purchasesCount": 0,
    "minPrice": 0,
    "downloadsCount": 328,
    "userId": 40551
  },
  "uploadId": 213893,
  "uploads": {
    "213893": {
      "filename": "flaw-model-editor-windows.zip",
      "updatedAt": "2016-08-26 06:29:14",
      "buildId": 5011,
      "id": 213893,
      "pOsx": false,
      "channelName": "model-editor-windows",
      "position": 2,
      "gameId": 68784,
      "preorder": false,
      "pWindows": true,
      "createdAt": "2016-05-24 17:58:30",
      "size": 2644288,
      "pLinux": false,
      "type": "default",
      "build": {
        "parentBuildId": 4901,
        "updatedAt": "2016-08-26 06:28:49",
        "version": 29,
        "id": 5011,
        "state": "completed",
        "user": {
          "url": "https://quyse.itch.io",
          "username": "quyse",
          "id": 40551,
          "coverUrl": "https://img.itch.io/aW1hZ2UyL3VzZXIvNDA1NTEvMTE5MDU0LmpwZw==/100x100%23/EVUySj.jpg"
        },
        "files": [
          {
            "updatedAt": "2016-08-26 06:29:04",
            "size": 3485,
            "id": 14904,
            "type": "signature",
            "subType": "default",
            "createdAt": "2016-08-26 06:28:51",
            "state": "uploaded"
          },
          {
            "updatedAt": "2016-08-26 06:29:04",
            "size": 2332927,
            "id": 14903,
            "type": "patch",
            "subType": "default",
            "createdAt": "2016-08-26 06:28:50",
            "state": "uploaded"
          },
          {
            "updatedAt": "2016-08-26 06:29:14",
            "size": 2644288,
            "id": 14907,
            "type": "archive",
            "subType": "default",
            "createdAt": "2016-08-26 06:29:06",
            "state": "uploaded"
          }
        ],
        "createdAt": "2016-08-26 06:28:49"
      },
      "pAndroid": false,
      "demo": false,
      "score": 600
    }
  },
  "installLocation": "appdata",
  "installFolder": "FLAW",
  "pathScheme": 2,
  "handPicked": false,
  "fresh": true
}
[2016-08-26 @ 07:25:29.241] [installers/exe] found cached installer type undefined
[2016-08-26 @ 07:25:29.242] [installers/exe] invalid exe type stored: undefined - discarding
[2016-08-26 @ 07:25:29.386] [reactors/tasks] Task threw
[2016-08-26 @ 07:25:29.386] [reactors/tasks] Task ended, err: Error: lsar failed with code 1
    at Function.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\util\spawn.js:119:11)
From previous event:
    at Function.spawn.getOutput (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\util\spawn.js:113:1)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\exe.js:131:34)
    at next (native)
From previous event:
    at Object.externalSniff (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\exe.js:126:3)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\exe.js:82:25)
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Object.identify (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\exe.js:79:3)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\exe.js:36:25)
    at next (native)
From previous event:
    at Object.findInstaller (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\exe.js:25:3)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\exe.js:16:32)
    at next (native)
From previous event:
    at Object.install (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\exe.js:15:3)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\core.js:153:11)
From previous event:
    at Object.operate (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\core.js:138:3)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\core.js:48:23)
    at next (native)
From previous event:
    at Object.install (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\core.js:47:3)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\archive.js:123:16)
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Object.handleNested (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\archive.js:107:3)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\archive.js:75:25
    at next (native)
From previous event:
    at deployOpts.onSingle (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\archive.js:74:5)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\util\deploy.js:36:23)
    at next (native)
    at f (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\once\once.js:17:25)
    at Glob.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\glob\glob.js:147:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\glob\glob.js:195:8)
    at done (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\glob\glob.js:180:14)
    at Glob._processGlobStar2 (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\glob\glob.js:632:12)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\glob\glob.js:621:10
    at RES (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\inflight\inflight.js:23:14)
From previous event:
    at Object.deploy (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\util\deploy.js:27:3)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\archive.js:78:18)
From previous event:
    at Object.install (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\archive.js:48:3)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\core.js:153:11)
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Object.operate (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\core.js:138:3)
    at Object.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\core.js:48:23)
    at next (native)
From previous event:
    at Object.install (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install\core.js:47:3)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\tasks\install.js:104:14
    at next (native)
    at FSReqWrap.oncomplete (original-fs.js:117:15)
From previous event:
    at start (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\app\tasks\install.js:166:17)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\tasks\start-task.js:53:20
    at next (native)
From previous event:
    at startTask (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\app\reactors\tasks\start-task.js:67:17)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\tasks\download-ended.js:47:27
    at next (native)
From previous event:
    at downloadEnded (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\app\reactors\tasks\download-ended.js:61:17)
From previous event:
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\combine.js:20:15
    at next (native)
From previous event:
    at _underline.each.call (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\combine.js:18:5)
    at _.each._.forEach (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:153:9)
    at Array.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\underline.js:23:14)
    at executeBound (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:701:67)
    at Array.bound (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:733:14)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\combine.js:18:5
    at route (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\route.js:5:5)
    at postDispatchCallback (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\store\browser-store.js:46:7)
    at doDispatch (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:146:11)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\tasks\download-watcher.js:120:11
From previous event:
    at start (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\app\reactors\tasks\download-watcher.js:127:18)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\tasks\download-watcher.js:48:7
From previous event:
    at updateDownloadState (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\app\reactors\tasks\download-watcher.js:61:18)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\tasks\download-watcher.js:25:13
    at next (native)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at downloadWatcher (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\app\reactors\tasks\download-watcher.js:24:17)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\tasks\index.js:15:9
    at next (native)
From previous event:
    at boot (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\app\reactors\tasks\index.js:15:17)
From previous event:
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\combine.js:20:15
    at next (native)
From previous event:
    at _underline.each.call (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\combine.js:18:5)
    at _.each._.forEach (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:153:9)
    at Array.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\underline.js:23:14)
    at executeBound (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:701:67)
    at Array.bound (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:733:14)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\combine.js:18:5
    at route (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\route.js:5:5)
    at postDispatchCallback (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\store\browser-store.js:46:7)
    at doDispatch (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:146:11)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\preboot.js:47:9
    at throw (native)
From previous event:
    at preboot (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\app\reactors\preboot.js:56:17)
From previous event:
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\combine.js:20:15
    at next (native)
From previous event:
    at _underline.each.call (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\combine.js:18:5)
    at _.each._.forEach (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:153:9)
    at Array.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\underline.js:23:14)
    at executeBound (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:701:67)
    at Array.bound (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\underline\node_modules\underscore\underscore.js:733:14)
    at C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\combine.js:18:5
    at route (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\reactors\route.js:5:5)
    at postDispatchCallback (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\store\browser-store.js:46:7)
    at doDispatch (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:146:11)
    at EventEmitter.<anonymous> (C:\Users\gitlab-runner\AppData\Local\itch\app-18.6.1\resources\app.asar\appsrc\metal.js:64:11)
    at next (native)
From previous event:
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
[2016-08-26 @ 07:25:29.389] [reactors/tasks] Error in task install: Error: lsar failed with code 1
[2016-08-26 @ 07:25:29.389] [reactors/tasks] Install failed, attempting to destroy cave
[2016-08-26 @ 07:25:29.395] [reactors/tasks] Error in install: Error: lsar failed with code 1
[2016-08-26 @ 07:40:06.307] [reactors/fetch] Fetching the usuals
[2016-08-26 @ 07:52:21.113] [reactors/fetch] Fetching the usuals
[2016-08-26 @ 07:55:30.007] [reactors/fetch] Fetching the usuals
```

I tried to run `lsar` manually:

```
C:\Users\gitlab-runner\AppData\Roaming\itch\downloads>C:\Users\gitlab-runner\AppData\Roaming\itch\bin\unarchiver\lsar.exe 213893-5011.zip
213893-5011.zip: 2016-08-26 08:10:21.452 lsar[3944:1232] File NSCalendarDate.m: 1546. In -[NSCalendarDate initWit
hYear:month:day:hour:minute:second:timeZone:] invalid month given - 0
2016-08-26 08:10:21.452 lsar[3944:1232] File NSCalendarDate.m: 1551. In -[NSCalendarDate initWithYear:month:day:h
our:minute:second:timeZone:] invalid day given - 0
Zip
model-editor.exe
```

Apart from strange messages about zero month and day (they go to stderr anyway), it works (and exits with zero code actually).

**Comment by fasterthanlime** [comment]
There was an issue about stderr filling up some nodejs buffer and then nodejs silently killing off the lsar process, but it shouldn't be present in the latest itch. What version of the itch app is that?

**Comment by fasterthanlime** [comment]
Oh wait no, it's trying to use lsar to identify if the executable is a self-extracting archive, and that fails, that's a different issue.

**Comment by quyse** [comment]
Version is latest, v18.6.1.

**Comment by fasterthanlime** [comment]
@quyse 18.6.2 is out and fixes this issue https://github.com/itchio/itch/releases/tag/v18.6.2

**Comment by quyse** [comment]
@fasterthanlime I confirm, seems working now, thanks Amos!
