### ISSUE TITLE
HTTP 400 on /me with proxy enabled

### ISSUE THREAD

**Issue by tomhoward87** [itchio/itch#962]
I get this error when trying to log in - it seems to be making the request ok as it tells me when I get my password wrong.

`Error: HTTP 400 /<removed potentially identifying string>/me
    at Client.<anonymous> (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrcts\util\api.ts:108:13)
    at next (<anonymous>)
    at fulfilled (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\app\util\api.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From previous event:
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at loginWithPassword (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\app\reactors\login.js:28:17)
From previous event:
    at C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\combine.js:20:15
    at next (<anonymous>)
From previous event:
    at _underline.each.call (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\combine.js:18:5)
    at _.each._.forEach (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underscore\underscore.js:153:9)
    at Array.<anonymous> (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underline\underline.js:23:14)
    at executeBound (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underscore\underscore.js:701:67)
    at Array.bound (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underscore\underscore.js:733:14)
    at C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\combine.js:18:5
    at route (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\route.js:5:5)
    at postDispatchCallback (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrcts\store\browser-store.ts:51:7)
    at doDispatch (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:146:11)
    at EventEmitter.<anonymous> (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:129:15)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (C:\Users\gbhowarto\AppData\Local\itch\app-19.0.0\resources\electron.asar\browser\api\web-contents.js:210:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)`

**Comment by fasterthanlime** [comment]
Are you behind a proxy?

**Comment by tomhoward87** [comment]
Yes. I have the Linux version 18.10.1 running on a machine on the same network with no issues though.

**Comment by fasterthanlime** [comment]
Do you know what software the proxy is running? I'll try to reproduce and issue a fix as soon as I can find the issue.

**Comment by tomhoward87** [comment]
Hmm, I'm not sure, I think it's Bluecoat? I was able to temporarily disable it and the app works now (on Windows). My Linux machine isn't using the proxy, so that explains why it worked there.

**Comment by fasterthanlime** [comment]
Great, so the issue is only when using a proxy. I think I'll be able to reproduce it pretty easily — fix might come in slower than usual since I'm in the middle of a refactor but I'll try to get it out quickly nonetheless.

**Comment by tomhoward87** [comment]
No worries, knowing I can disable it is enough for my testing purposes. Thanks!

**Comment by fasterthanlime** [comment]
I'm still interested in that issue though! Reopening :) Feel free to mute it if you want to avoid notifications!

**Comment by tomhoward87** [comment]
Whoops, sorry!

**Comment by fasterthanlime** [comment]
> My Linux machine isn't using the proxy, so that explains why it worked there.

Hmm so, you might have the same issue on Windows with 18.10.1? I just tried with Fiddler running on another machine and the proxy works fine. However, we have another pending issue: #942, which sounds like it might be related!
