### ISSUE TITLE
Some java games need CWD to be set to the .jar's directory to run

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch#969]
See https://github.com/itchio/itch-compatibility-watchlist/issues/239 

This works:

```
amos at dople in /tmp/snw/snw
$ java -jar SuperKnightWorld.jar
```

this doesn't:

```
amos at dople in /tmp/snw
$ java -jar snw/SuperKnightWorld.jar
java.io.FileNotFoundException: data/snd/swish.wav (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.sun.media.sound.WaveFloatFileReader.getAudioInputStream(WaveFloatFileReader.java:164)
        at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1181)
        at superknightworld.view.Sfx.getResources(Sfx.java:33)
        at superknightworld.model.Game.initialize(Game.java:203)
        at superknightworld.controller.Controller.<init>(Controller.java:33)
        at superknightworld.Main.main(Main.java:17)
Exception in thread "main" java.lang.NullPointerException
        at superknightworld.view.Sfx.startMenu(Sfx.java:96)
        at superknightworld.model.Game.initialize(Game.java:204)
        at superknightworld.controller.Controller.<init>(Controller.java:33)
        at superknightworld.Main.main(Main.java:17)
```

Should be an easy fix :)

**Comment by fasterthanlime** [comment]
Actually! on macOS, the sandbox is used to run java games, and so it doesn't find any runtime environments. Need to adjust the template file.
