### ISSUE TITLE
Updater not working if installedAt field is not set

### ISSUE THREAD

**Issue by koesie10** [itchio/itch#977]
I haven't started Itch for a while, but now when I start it I can't get updates for e.g. Kenney Game Assets 2. The version I am now using is 19.0.0.

Whenever I do a manual update, I get the following message in the itch-updater log (I have KGA2 version 10 installed):

```
[2016-11-08 @ 18:15:38.456] [updater] Looking for updates for cave 94e48f78-74ec-47af-8af9-58b3b13f2a41
[2016-11-08 @ 18:15:38.458] [updater] Looking for updates to Kenney Game Assets 2...
[2016-11-08 @ 18:15:38.618] [updater] installed at 2016-11-08T17:15:38Z
[2016-11-08 @ 18:15:38.623] [updater] Filtering out Kenney Game Assets 2 version 15.zip (#311863), 2016-11-04T17:05:17Z is older than 2016-11-08T17:15:38Z
[2016-11-08 @ 18:15:38.625] [updater] Filtering out KGA2 Games version 2.zip (#256115), 2016-08-18T00:18:09Z is older than 2016-11-08T17:15:38Z
[2016-11-08 @ 18:15:38.625] [updater] 2 available uploads, 0 are more recent
[2016-11-08 @ 18:15:38.626] [updater] No recent uploads for Kenney Game Assets 2, update check done
[2016-11-08 @ 18:15:38.630] [updater] Done looking for updates for cave 94e48f78-74ec-47af-8af9-58b3b13f2a41
```

Basically, the installed at is just the current time, but in UTC.

I'm using Windows 10.

**Comment by fasterthanlime** [comment]
Oh.. I think `moment()` gives current time instead of 1970-01-01 if the input you give it is null.

I'll look into it, thanks!

**Comment by fasterthanlime** [comment]
(Note: in the meantime, you can work around it for yourself by just uninstalling Kenney Game Assets and re-installing it!)

**Comment by koesie10** [comment]
Alright, thanks!

By the way, when I just click Reinstall in the app, it also doesn't work so I really need to click Unininstall now and then Install.

**Comment by fasterthanlime** [comment]
Like I thought:

![screen shot 2016-11-08 at 22 05 20](https://cloud.githubusercontent.com/assets/7998310/20117124/7fede380-a5ff-11e6-96d2-b203a173b123.png)

🐼 

> By the way, when I just click Reinstall in the app, it also doesn't work so I really need to click Uninstall now and then Install.

Did you remember what it does and/or can you peek in %APPDATA%/itch/logs/itch.log.txt to see what happened?

**Comment by koesie10** [comment]
> Did you remember what it does and/or can you peek in %APPDATA%/itch/logs/itch.log.txt to see what happened?

I think this is the log of the reinstall:

```
[2016-11-08 @ 18:23:00.074] [reactors/tasks] About to start find-upload (6ecab16d-a4c3-4f62-a83c-dfdecab44954)
[2016-11-08 @ 18:23:00.074] [reactors/tasks] Starting find-upload (6ecab16d-a4c3-4f62-a83c-dfdecab44954)...
[2016-11-08 @ 18:23:00.234] [tasks/find-upload] got a list of 2 uploads (with download key)
[2016-11-08 @ 18:23:00.234] [tasks/find-upload] final uploads: [
  {
    "filename": "Kenney Game Assets 2 version 15.zip",
    "updatedAt": "2016-11-04 17:05:17",
    "position": 0,
    "id": 311863,
    "pOsx": false,
    "demo": false,
    "createdAt": "2016-11-04 17:02:32",
    "pWindows": false,
    "gameId": 32803,
    "preorder": false,
    "pLinux": false,
    "type": "default",
    "displayName": "Kenney Game Assets 2 (version 15)",
    "size": 94619706,
    "pAndroid": false,
    "score": 600
  },
  {
    "filename": "KGA2 Games version 2.zip",
    "updatedAt": "2016-08-18 00:18:09",
    "position": 1,
    "id": 256115,
    "pOsx": false,
    "demo": false,
    "createdAt": "2016-08-18 00:16:43",
    "pWindows": true,
    "gameId": 32803,
    "preorder": false,
    "pLinux": false,
    "type": "default",
    "displayName": "Kenney Game Assets 2 (game launcher, version 2)",
    "size": 46349593,
    "pAndroid": false,
    "score": 600
  }
]
[2016-11-08 @ 18:23:00.234] [reactors/tasks] Checking results for find-upload (6ecab16d-a4c3-4f62-a83c-dfdecab44954)...
[2016-11-08 @ 18:23:00.234] [reactors/tasks] Task results: {
  "uploads": [
    {
      "filename": "Kenney Game Assets 2 version 15.zip",
      "updatedAt": "2016-11-04 17:05:17",
      "position": 0,
      "id": 311863,
      "pOsx": false,
      "demo": false,
      "createdAt": "2016-11-04 17:02:32",
      "pWindows": false,
      "gameId": 32803,
      "preorder": false,
      "pLinux": false,
      "type": "default",
      "displayName": "Kenney Game Assets 2 (version 15)",
      "size": 94619706,
      "pAndroid": false,
      "score": 600
    },
    {
      "filename": "KGA2 Games version 2.zip",
      "updatedAt": "2016-08-18 00:18:09",
      "position": 1,
      "id": 256115,
      "pOsx": false,
      "demo": false,
      "createdAt": "2016-08-18 00:16:43",
      "pWindows": true,
      "gameId": 32803,
      "preorder": false,
      "pLinux": false,
      "type": "default",
      "displayName": "Kenney Game Assets 2 (game launcher, version 2)",
      "size": 46349593,
      "pAndroid": false,
      "score": 600
    }
  ],
  "downloadKey": {
    "updatedAt": "2016-01-22 16:37:22",
    "downloads": 8,
    "id": 339935,
    "purchaseId": 311566,
    "gameId": 32803,
    "createdAt": "2016-01-22 16:37:22"
  }
}
[2016-11-08 @ 18:23:00.234] [reactors/tasks] Task ended, err: <none>
[2016-11-08 @ 18:23:00.237] [reactors/tasks] Should download 311863, has dl key ? true
[2016-11-08 @ 18:23:00.240] [reactors/tasks] About to start install (6d3d2fef-b2c3-4028-a31e-fd824af2895a)
[2016-11-08 @ 18:23:00.240] [reactors/tasks] Starting install (6d3d2fef-b2c3-4028-a31e-fd824af2895a)...
[2016-11-08 @ 18:23:00.240] [tasks/install] upgrading from build id undefined => build id undefined
[2016-11-08 @ 18:23:00.247] [tasks/install] where did our archive go? re-downloading...
[2016-11-08 @ 18:23:00.248] [reactors/tasks] Task threw
[2016-11-08 @ 18:23:00.248] [reactors/tasks] Task ended, err: Transition(to download because missing-download)
    at C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\tasks\install.js:95:13
    at throw (<anonymous>)
From previous event:
    at start (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\app\tasks\install.js:181:17)
    at C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\tasks\start-task.js:53:20
    at next (<anonymous>)
From previous event:
    at startTask (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\app\reactors\tasks\start-task.js:67:17)
    at C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\tasks\queue-cave-reinstall.js:50:9
    at next (<anonymous>)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at queueCaveReinstall (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\app\reactors\tasks\queue-cave-reinstall.js:61:17)
From previous event:
    at C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\combine.js:20:15
    at next (<anonymous>)
From previous event:
    at _underline.each.call (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\combine.js:18:5)
    at _.each._.forEach (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underscore\underscore.js:153:9)
    at Array.<anonymous> (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underline\underline.js:23:14)
    at executeBound (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underscore\underscore.js:701:67)
    at Array.bound (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underscore\underscore.js:733:14)
    at C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\combine.js:18:5
    at route (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\route.js:5:5)
    at postDispatchCallback (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrcts\store\browser-store.ts:51:7)
    at doDispatch (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:146:11)
    at C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\modals.js:15:13
    at next (<anonymous>)
From previous event:
    at closeModal (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\app\reactors\modals.js:29:17)
From previous event:
    at C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\combine.js:20:15
    at next (<anonymous>)
From previous event:
    at _underline.each.call (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\combine.js:18:5)
    at _.each._.forEach (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underscore\underscore.js:153:9)
    at Array.<anonymous> (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underline\underline.js:23:14)
    at executeBound (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underscore\underscore.js:701:67)
    at Array.bound (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\underscore\underscore.js:733:14)
    at C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\combine.js:18:5
    at route (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrc\reactors\route.js:5:5)
    at postDispatchCallback (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrcts\store\browser-store.ts:51:7)
    at doDispatch (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:84:11)
    at Object.store.dispatch (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:146:11)
    at EventEmitter.<anonymous> (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\app.asar\node_modules\redux-electron-store\lib\electronBrowserEnhancer.js:129:15)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (C:\Users\Koen\AppData\Local\itch\app-19.0.0\resources\electron.asar\browser\api\web-contents.js:210:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
[2016-11-08 @ 18:23:00.249] [reactors/tasks] Error in task install: Transition(to download because missing-download)
[2016-11-08 @ 18:23:00.249] [reactors/tasks] Install failed, attempting to destroy cave
[2016-11-08 @ 18:23:00.251] [download-watcher] 7ce1c141-cfb8-4972-97e8-251d2ea24a93 is the new active download
[2016-11-08 @ 18:23:00.251] [download-watcher] Starting download...
[2016-11-08 @ 18:23:01.011] [butler] butler: Downloading 90 MiB
[2016-11-08 @ 18:23:01.011] [butler] butler: Resuming at 0 B / 90 MiB
[2016-11-08 @ 18:23:25.402] [reactors/fetch] Fetching the usuals
[2016-11-08 @ 18:23:36.469] [butler] butler: √ 0 B + 90 MiB copied @ 2.5 MiB/s

[2016-11-08 @ 18:23:36.474] [download-watcher] Download ended, err: <none>
[2016-11-08 @ 18:23:36.476] [reactors/tasks] Downloaded something for reason reinstall
[2016-11-08 @ 18:23:36.478] [download-watcher] Download done!
[2016-11-08 @ 18:23:36.568] [download-watcher] Cancelling/clearing out last download
```

**Comment by fasterthanlime** [comment]
Ah, I see, that sounds like a distinct bug, thanks!
