### ISSUE TITLE
marketdb: EPERM when renaming file on Windows

### ISSUE THREAD

**Issue by nickfourtimes** [itchio/itch#982]
Event log:

```
Error: EPERM: operation not permitted, rename 'C:\Users\Nick\AppData\Roaming\itch\users\952\marketdb\collections\680.tmp122' -> 'C:\Users\Nick\AppData\Roaming\itch\users\952\marketdb\collections\680'
    at Error (native)
From previous event:
    at Object.<anonymous> (C:\Users\Nick\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrcts\util\sf.ts:161:21)
    at next (<anonymous>)
    at C:\Users\Nick\AppData\Local\itch\app-19.0.0\resources\app.asar\app\util\sf.js:7:65
    at __awaiter (C:\Users\Nick\AppData\Local\itch\app-19.0.0\resources\app.asar\app\util\sf.js:3:12)
    at Object.rename (C:\Users\Nick\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrcts\util\sf.ts:160:50)
    at Market.<anonymous> (C:\Users\Nick\AppData\Local\itch\app-19.0.0\resources\app.asar\appsrcts\util\market.ts:312:16)
    at next (<anonymous>)
    at fulfilled (C:\Users\Nick\AppData\Local\itch\app-19.0.0\resources\app.asar\app\util\market.js:4:58)
```

**Comment by fasterthanlime** [comment]
I'm not sure when that could ever happen :(

**Comment by fasterthanlime** [comment]
Got an EPERM myself on Win10, when opening the log file for a game. In File Exporer, AppData\Roaming\kitch\cave-logs appears read-only :(

It's a mystery! (but a bad one)

**Comment by fasterthanlime** [comment]
I can reproduce this regularly on my Windows install now - it seems to happen when the same record is saved twice very quickly. I'm thinking about batching saves now, to avoid this.

**Comment by fasterthanlime** [comment]
marketdb is dead, itch v25 uses sqlite.
